CommandAction Class Reference
#include <CommandAction.h>
Public Member Functions
CommandAction ()
CommandAction (CommandAction *const other_)
CommandAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const WEAPONTYPE currentWeap_, BaseAction *const command_)
void OnDestroy ()
BaseAction * ReturnAction () const
WEAPONTYPE ReturnWeaponType () const
void SetCommand (BaseAction *action_)
void SetWeaponType (WEAPONTYPE type_)
~CommandAction ()
Detailed Description
Definition at line 18 of file CommandAction.h.
Constructor & Destructor Documentation
CommandAction() [1/3]
CommandAction::CommandAction ()
Definition at line 6 of file CommandAction.cpp.
                             : command(nullptr)
{
     SetName("");
     SetDiscription("");
     SetActionType(ACTIONTYPE::E_NONE);
     SetTargetType(TARGETTYPE::E_NONE);
     SetInteractionType(INTERACTIONTYPE::E_NONE);
     SetActionID(00);
     currentweapon = WEAPONTYPE::E_NONE;
}
CommandAction() [2/3]
CommandAction::CommandAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const WEAPONTYPE currentWeap_, BaseAction *const command_)
Definition at line 16 of file CommandAction.cpp.
{
     SetName(name_);
     SetDiscription(discription_);
     SetActionType(action_);
     SetTargetType(target_);
     SetInteractionType(interaction_);
     SetActionID(actionID_);
     currentweapon = currentWeap_;
     command = command_;
}
CommandAction() [3/3]
CommandAction::CommandAction (CommandAction *const other_)
Definition at line 27 of file CommandAction.cpp.
{
     SetName(other_->ReturnName());
     SetDiscription(other_->ReturnDiscription());
     SetActionType(other_->ReturnActionType());
     SetTargetType(other_->ReturnTargetType());
     SetInteractionType(other_->ReturnInteractionType());
     SetActionID(other_->ReturnActionID());
     currentweapon = ReturnWeaponType();
     command = ReturnAction();
}
 CommandAction()
CommandAction::~CommandAction ()
Definition at line 62 of file CommandAction.cpp.
{
     OnDestroy();
}
Member Function Documentation
OnDestroy()
void CommandAction::OnDestroy ()
Definition at line 54 of file CommandAction.cpp.
{
     if(command)
     {
          delete command;
          command = nullptr;
     }
}
Referenced by ~CommandAction().
ReturnAction()
BaseAction * CommandAction::ReturnAction () const
Definition at line 50 of file CommandAction.cpp.
{
     return command;
}
Referenced by CommandAction().
ReturnWeaponType()
WEAPONTYPE CommandAction::ReturnWeaponType () const
Definition at line 46 of file CommandAction.cpp.
{
     return currentweapon;
}
Referenced by CommandAction().
SetCommand()
void CommandAction::SetCommand (BaseAction * action_)
Definition at line 42 of file CommandAction.cpp.
{
     command = action_;
}
SetWeaponType()
void CommandAction::SetWeaponType (WEAPONTYPE type_)
Definition at line 38 of file CommandAction.cpp.
{
     currentweapon = type_;
}