ItemAction Class Reference
#include <ItemAction.h>
Public Member Functions
void AddEffect (AbilityAction *const ability_)
Adds an effect to the items effects array.
ItemAction ()
ItemAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const uint32 value_, const DAMAGETYPE damageType_, const TArray< AbilityAction * > effectArray_)
ItemAction (const ItemAction *other_)
void OnDestroy ()
DAMAGETYPE ReturnDamageType () const
Returns Damage type.
TArray< AbilityAction * > ReturnEffectList () const
Returns Effect array.
ITEMTYPE ReturnItemType () const
Returns itemType.
uint32 ReturnValue () const
Returnsitem value.
void SetDamageType (const DAMAGETYPE type_)
Set Damage type.
void SetType (const ITEMTYPE type_)
Set Item type.
void SetValue (const uint32 value_)
Set item Value.
~ItemAction ()
Detailed Description
Definition at line 21 of file ItemAction.h.
Constructor & Destructor Documentation
ItemAction() [1/3]
ItemAction::ItemAction ()
Definition at line 4 of file ItemAction.cpp.
                       : effectList(TArray<AbilityAction*>())
{
     SetName("");
     SetDiscription("");
     SetActionType(ACTIONTYPE::E_NONE);
     SetTargetType(TARGETTYPE::E_NONE);
     SetInteractionType(INTERACTIONTYPE::E_NONE);
     SetActionID(00);
     SetValue(00);
     SetDamageType(DAMAGETYPE::E_NONE);
}
ItemAction() [2/3]
ItemAction::ItemAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const uint32 value_, const DAMAGETYPE damageType_, const TArray< AbilityAction * > effectArray_)
Definition at line 15 of file ItemAction.cpp.
{
     SetName(name_);
     SetDiscription(discription_);
     SetActionType(action_);
     SetTargetType(target_);
     SetInteractionType(interaction_);
     SetActionID(actionID_);
     
     value = value_;
     effectList = effectArray_;
}
ItemAction() [3/3]
ItemAction::ItemAction (const ItemAction * other_)
Definition at line 28 of file ItemAction.cpp.
{
     SetName(other_->ReturnName());
     SetDiscription(other_->ReturnDiscription());
     SetActionType(other_ ->ReturnActionType());
     SetTargetType(other_->ReturnTargetType());
     SetInteractionType(other_->ReturnInteractionType());
     SetActionID(other_->ReturnActionID());
     SetValue(other_->ReturnValue());
}
 ItemAction()
ItemAction::~ItemAction ()
Definition at line 78 of file ItemAction.cpp.
{
     OnDestroy();
}
Member Function Documentation
AddEffect()
void ItemAction::AddEffect (AbilityAction *const ability_)
Adds an effect to the items effects array.
Definition at line 50 of file ItemAction.cpp.
{
     effectList.Add(ability_);
}
OnDestroy()
void ItemAction::OnDestroy ()
Definition at line 74 of file ItemAction.cpp.
{
     //Clean up method
}
Referenced by ~ItemAction().
ReturnDamageType()
DAMAGETYPE ItemAction::ReturnDamageType () const
Returns Damage type.
Definition at line 62 of file ItemAction.cpp.
{
     return damageType;
}
ReturnEffectList()
TArray< AbilityAction * > ItemAction::ReturnEffectList () const
Returns Effect array.
Definition at line 70 of file ItemAction.cpp.
{
     return effectList;
}
ReturnItemType()
ITEMTYPE ItemAction::ReturnItemType () const
Returns itemType.
Definition at line 54 of file ItemAction.cpp.
{
     return type;
}
Referenced by DamageDeltSystem::BaseCalculate().
ReturnValue()
uint32 ItemAction::ReturnValue () const
Returnsitem value.
Definition at line 58 of file ItemAction.cpp.
{
     return value;
}
Referenced by ItemAction().
SetDamageType()
void ItemAction::SetDamageType (const DAMAGETYPE type_)
Set Damage type.
Definition at line 42 of file ItemAction.cpp.
{
     damageType = type_;
}
Referenced by ItemAction().
SetType()
void ItemAction::SetType (const ITEMTYPE type_)
Set Item type.
Definition at line 46 of file ItemAction.cpp.
{
     type = type_;
}
SetValue()
void ItemAction::SetValue (const uint32 value_)
Set item Value.
Definition at line 38 of file ItemAction.cpp.
{
     value = value_;
}
Referenced by ItemAction().