.TH "AbilityAction" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbilityAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbilityAction\fP (\fBAbilityAction\fP *const other_)"
.br
.ti -1c
.RI "\fBAbilityAction\fP (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const float duration_)"
.br
.ti -1c
.RI "float \fBCalculateAbilityValue\fP ()"
.br
.ti -1c
.RI "float \fBReturnDuration\fP () const"
.br
.ti -1c
.RI "void \fBSetDuration\fP (const float duration_)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBabilityValue\fP"
.br
.ti -1c
.RI "float \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file AbilityAction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
