.TH "BaseSystem" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseSystem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseSystem\&.h>\fP
.PP
Inherited by \fBDamageDeltSystem\fP, \fBEffectSystem\fP, and \fBStatSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBBaseCalculate\fP (const bool IsSingledTarget_, \fBBaseAction\fP *const action_)=0"
.br
.RI "Base calculation for any dirieved system classes\&. "
.ti -1c
.RI "virtual \fB~BaseSystem\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file BaseSystem\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual BaseSystem::~BaseSystem ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 12 of file BaseSystem\&.h\&.
.PP
.nf
12 {};
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void BaseSystem::BaseCalculate (const bool IsSingledTarget_, \fBBaseAction\fP *const action_)\fC [pure virtual]\fP"

.PP
Base calculation for any dirieved system classes\&. 
.PP
Implemented in \fBEffectSystem\fP, \fBStatSystem\fP, and \fBDamageDeltSystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
