.TH "BaseAction" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseAction
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbilityAction\fP, \fBCommandAction\fP, and \fBItemAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseAction\fP (const \fBBaseAction\fP *other_)"
.br
.ti -1c
.RI "\fBBaseAction\fP (FString name_, FString discription_, ACTIONTYPE action_, TARGETTYPE target_, INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_)"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "uint32 \fBReturnActionID\fP () const"
.br
.ti -1c
.RI "ACTIONTYPE \fBReturnActionType\fP () const"
.br
.ti -1c
.RI "FString \fBReturnDiscription\fP () const"
.br
.ti -1c
.RI "INTERACTIONTYPE \fBReturnInteractionType\fP () const"
.br
.ti -1c
.RI "FString \fBReturnName\fP () const"
.br
.ti -1c
.RI "TMap< FString, float > \fBReturnStatMap\fP () const"
.br
.ti -1c
.RI "TARGETTYPE \fBReturnTargetType\fP () const"
.br
.ti -1c
.RI "void \fBSetActionID\fP (const uint32 actionID_)"
.br
.ti -1c
.RI "void \fBSetActionType\fP (const ACTIONTYPE type_)"
.br
.ti -1c
.RI "void \fBSetDiscription\fP (const FString discription_)"
.br
.ti -1c
.RI "void \fBSetInteractionType\fP (const INTERACTIONTYPE type_)"
.br
.ti -1c
.RI "void \fBSetName\fP (const FString name_)"
.br
.ti -1c
.RI "void \fBSetTargetType\fP (const TARGETTYPE type_)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ACTIONTYPE \fBaction\fP"
.br
.ti -1c
.RI "uint32 \fBactionID\fP"
.br
.ti -1c
.RI "FString \fBdiscription\fP"
.br
.ti -1c
.RI "INTERACTIONTYPE \fBinteraction\fP"
.br
.ti -1c
.RI "FString \fBname\fP"
.br
.ti -1c
.RI "TMap< FString, float > \fBstatMap\fP"
.br
.ti -1c
.RI "TARGETTYPE \fBtarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file BaseAction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
