.TH "Battle_Box" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModuleRules\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBattle_Box\fP (ReadOnlyTargetRules Target)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Battle_Box\&.Build\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
