.TH "Battle_Box/Private/BattleBoxFileManager.cpp" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/BattleBoxFileManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BattleBoxFileManager\&.h'\fP
.br
\fC#include 'HAL/PlatformFilemanager\&.h'\fP
.br
\fC#include 'GenericPlatform/GenericPlatformFile\&.h'\fP
.br
\fC#include 'Misc/FileHelper\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
