.TH "Battle_Box/Private/BattleBoxFileManager.h" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/BattleBoxFileManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleBoxFileManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
