.TH "Battle_Box" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModuleRules\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBattle_Box\fP (ReadOnlyTargetRules Target)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Battle_Box\&.Build\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Battle_Box\&.Battle_Box (ReadOnlyTargetRules Target)\fC [inline]\fP"

.PP
Definition at line 7 of file Battle_Box\&.Build\&.cs\&.
.PP
.nf
7                                                    : base(Target)
8      {
9           PCHUsage = ModuleRules\&.PCHUsageMode\&.UseExplicitOrSharedPCHs;
10           
11           PublicIncludePaths\&.AddRange(
12                new string[] {
13                     // \&.\&.\&. add public include paths required here \&.\&.\&.
14                }
15                );
16                     
17           
18           PrivateIncludePaths\&.AddRange(
19                new string[] {
20                     // \&.\&.\&. add other private include paths required here \&.\&.\&.
21                }
22                );
23                
24           
25           PublicDependencyModuleNames\&.AddRange(
26                new string[]
27                {
28                     "Core",
29                 "BB_Runtime_System"
30                     // \&.\&.\&. add other public dependencies that you statically link with here \&.\&.\&.
31                }
32                );
33                
34           
35           PrivateDependencyModuleNames\&.AddRange(
36                new string[]
37                {
38                     "CoreUObject",
39                     "Engine",
40                     "Slate",
41                     "SlateCore",
42                 "BB_Runtime_System"
43                     // \&.\&.\&.   add private dependencies that you statically link with here \&.\&.\&.    
44                }
45                );
46           
47           
48           DynamicallyLoadedModuleNames\&.AddRange(
49                new string[]
50                {
51                     // \&.\&.\&. add any modules that your module loads dynamically here \&.\&.\&.
52                }
53                );
54      }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
