.TH "Battle_Box/Private/Battle_Box.cpp" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/Battle_Box.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Battle_Box\&.h'\fP
.br
\fC#include '\&.\&./Private/Debugger\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOCTEXT_NAMESPACE\fP   'FBattle_BoxModule'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOCTEXT_NAMESPACE   'FBattle_BoxModule'"

.PP
Definition at line 6 of file Battle_Box\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
