.TH "BB_Runtime_System" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BB_Runtime_System
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModuleRules\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBB_Runtime_System\fP (ReadOnlyTargetRules Target)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file BB_Runtime_System\&.Build\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
