.TH "Battle_Box/Private/ActionClasses/CommandAction.h" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/ActionClasses/CommandAction.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'BaseAction\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandAction\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWEAPONTYPE\fP { \fBWEAPONTYPE::E_NONE\fP, \fBWEAPONTYPE::E_BLADE\fP, \fBWEAPONTYPE::E_RANGE\fP, \fBWEAPONTYPE::E_BLUNT_WEAP\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBWEAPONTYPE\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIE_NONE \fP\fP
.TP
\fB\fIE_BLADE \fP\fP
.TP
\fB\fIE_RANGE \fP\fP
.TP
\fB\fIE_BLUNT_WEAP \fP\fP
.PP
Definition at line 8 of file CommandAction\&.h\&.
.PP
.nf
9 {
10      E_NONE,
11      E_BLADE,
12      E_RANGE,
13      E_BLUNT_WEAP
14 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
