.TH "CommandAction" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandAction\fP (\fBCommandAction\fP *const other_)"
.br
.ti -1c
.RI "\fBCommandAction\fP (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const WEAPONTYPE currentWeap_, \fBBaseAction\fP *const command_)"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "\fBBaseAction\fP * \fBReturnAction\fP () const"
.br
.ti -1c
.RI "WEAPONTYPE \fBReturnWeaponType\fP () const"
.br
.ti -1c
.RI "void \fBSetCommand\fP (\fBBaseAction\fP *action_)"
.br
.ti -1c
.RI "void \fBSetWeaponType\fP (WEAPONTYPE type_)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBaseAction\fP * \fBcommand\fP"
.br
.ti -1c
.RI "WEAPONTYPE \fBcurrentweapon\fP"
.br
.ti -1c
.RI "bool \fBisActionCommand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file CommandAction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
