.TH "Battle_Box Directory Reference" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBPrivate\fP"
.br
.ti -1c
.RI "directory \fBPublic\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBattle_Box\&.Build\&.cs\fP"
.br
.in -1c
