.TH "Battle_Box/Private/Debugger.h" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/Debugger.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugger\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMessageType\fP { \fBMessageType::E_NONE\fP = 0, \fBMessageType::E_INFO\fP, \fBMessageType::E_WARNING\fP, \fBMessageType::E_ERROR\fP, \fBMessageType::E_FATAL_ERROR\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMessageType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIE_NONE \fP\fP
.TP
\fB\fIE_INFO \fP\fP
.TP
\fB\fIE_WARNING \fP\fP
.TP
\fB\fIE_ERROR \fP\fP
.TP
\fB\fIE_FATAL_ERROR \fP\fP
.PP
Definition at line 9 of file Debugger\&.h\&.
.PP
.nf
10 {
11      E_NONE = 0,
12      E_INFO,
13      E_WARNING,
14      E_ERROR,
15      E_FATAL_ERROR
16 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
