.TH "BB_Runtime_System/Private/SystemClasses/EffectSystem.h" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BB_Runtime_System/Private/SystemClasses/EffectSystem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BaseSystem\&.h'\fP
.br
\fC#include 'Containers/Array\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffectSystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
