.TH "ItemAction" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddEffect\fP (\fBAbilityAction\fP *const ability_)"
.br
.RI "Adds an effect to the items effects array\&. "
.ti -1c
.RI "\fBItemAction\fP (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const uint32 value_, const DAMAGETYPE damageType_, const TArray< \fBAbilityAction\fP * > effectArray_)"
.br
.ti -1c
.RI "\fBItemAction\fP (const \fBItemAction\fP *other_)"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "DAMAGETYPE \fBReturnDamageType\fP () const"
.br
.RI "Returns Damage type\&. "
.ti -1c
.RI "TArray< \fBAbilityAction\fP * > \fBReturnEffectList\fP () const"
.br
.RI "Returns Effect array\&. "
.ti -1c
.RI "ITEMTYPE \fBReturnItemType\fP () const"
.br
.RI "Returns itemType\&. "
.ti -1c
.RI "uint32 \fBReturnValue\fP () const"
.br
.RI "Returnsitem value\&. "
.ti -1c
.RI "void \fBSetDamageType\fP (const DAMAGETYPE type_)"
.br
.RI "Set Damage type\&. "
.ti -1c
.RI "void \fBSetType\fP (const ITEMTYPE type_)"
.br
.RI "Set Item type\&. "
.ti -1c
.RI "void \fBSetValue\fP (const uint32 value_)"
.br
.RI "Set item Value\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "DAMAGETYPE \fBdamageType\fP"
.br
.ti -1c
.RI "TArray< \fBAbilityAction\fP * > \fBeffectList\fP"
.br
.ti -1c
.RI "ITEMTYPE \fBtype\fP"
.br
.ti -1c
.RI "uint32 \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file ItemAction\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void ItemAction::AddEffect (\fBAbilityAction\fP *const ability_)"

.PP
Adds an effect to the items effects array\&. 
.PP
Definition at line 50 of file ItemAction\&.cpp\&.
.PP
.nf
51 {
52      effectList\&.Add(ability_);
53 }
.fi
.SS "DAMAGETYPE ItemAction::ReturnDamageType () const"

.PP
Returns Damage type\&. 
.PP
Definition at line 62 of file ItemAction\&.cpp\&.
.PP
.nf
63 {
64      return damageType;
65 }
.fi
.SS "TArray< \fBAbilityAction\fP * > ItemAction::ReturnEffectList () const"

.PP
Returns Effect array\&. 
.PP
Definition at line 70 of file ItemAction\&.cpp\&.
.PP
.nf
71 {
72      return effectList;
73 }
.fi
.SS "ITEMTYPE ItemAction::ReturnItemType () const"

.PP
Returns itemType\&. 
.PP
Definition at line 54 of file ItemAction\&.cpp\&.
.PP
.nf
55 {
56      return type;
57 }
.fi
.SS "uint32 ItemAction::ReturnValue () const"

.PP
Returnsitem value\&. 
.PP
Definition at line 58 of file ItemAction\&.cpp\&.
.PP
.nf
59 {
60      return value;
61 }
.fi
.SS "void ItemAction::SetDamageType (const DAMAGETYPE type_)"

.PP
Set Damage type\&. 
.PP
Definition at line 42 of file ItemAction\&.cpp\&.
.PP
.nf
43 {
44      damageType = type_;
45 }
.fi
.SS "void ItemAction::SetType (const ITEMTYPE type_)"

.PP
Set Item type\&. 
.PP
Definition at line 46 of file ItemAction\&.cpp\&.
.PP
.nf
47 {
48      type = type_;
49 }
.fi
.SS "void ItemAction::SetValue (const uint32 value_)"

.PP
Set item Value\&. 
.PP
Definition at line 38 of file ItemAction\&.cpp\&.
.PP
.nf
39 {
40      value = value_;
41 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
