.TH "Battle_Box/Private/ActionClasses/ItemAction.h" 3 "Sat Jan 25 2020" "Battle Box Manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Battle_Box/Private/ActionClasses/ItemAction.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoreMinimal\&.h'\fP
.br
\fC#include 'BaseAction\&.h'\fP
.br
\fC#include 'Containers/Array\&.h'\fP
.br
\fC#include 'Containers/Map\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItemAction\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBITEMTYPE\fP { \fBITEMTYPE::E_NONE\fP, \fBITEMTYPE::E_CONSUMABLE\fP, \fBITEMTYPE::E_ARMOR\fP, \fBITEMTYPE::E_WEAPON\fP, \fBITEMTYPE::E_KEY_ITEM\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBITEMTYPE\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIE_NONE \fP\fP
.TP
\fB\fIE_CONSUMABLE \fP\fP
.TP
\fB\fIE_ARMOR \fP\fP
.TP
\fB\fIE_WEAPON \fP\fP
.TP
\fB\fIE_KEY_ITEM \fP\fP
.PP
Definition at line 13 of file ItemAction\&.h\&.
.PP
.nf
14 {
15      E_NONE,
16      E_CONSUMABLE,
17      E_ARMOR,
18      E_WEAPON,
19      E_KEY_ITEM
20 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle Box Manual from the source code\&.
