BaseAction Class Reference
#include <BaseAction.h>
Public Member Functions
BaseAction ()
BaseAction (const BaseAction *other_)
BaseAction (FString name_, FString discription_, ACTIONTYPE action_, TARGETTYPE target_, INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_)
void OnDestroy ()
uint32 ReturnActionID () const
ACTIONTYPE ReturnActionType () const
FString ReturnDiscription () const
INTERACTIONTYPE ReturnInteractionType () const
FString ReturnName () const
TMap< FString, float > ReturnStatMap () const
TARGETTYPE ReturnTargetType () const
void SetActionID (const uint32 actionID_)
void SetActionType (const ACTIONTYPE type_)
void SetDiscription (const FString discription_)
void SetInteractionType (const INTERACTIONTYPE type_)
void SetName (const FString name_)
void SetTargetType (const TARGETTYPE type_)
virtual ~BaseAction ()
Detailed Description
Definition at line 56 of file BaseAction.h.
Constructor & Destructor Documentation
BaseAction() [1/3]
BaseAction::BaseAction ()
Definition at line 6 of file BaseAction.cpp.
{
     name = "";
     discription = "";
     action = ACTIONTYPE::E_NONE;
     target = TARGETTYPE::E_NONE;
     interaction = INTERACTIONTYPE::E_NONE;
     actionID = 00;
}
BaseAction() [2/3]
BaseAction::BaseAction (FString name_, FString discription_, ACTIONTYPE action_, TARGETTYPE target_, INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_)
Definition at line 15 of file BaseAction.cpp.
{
     name = name_;
     discription = discription_;
     action = action_;
     target = target_;
     interaction = interaction_;
     actionID = actionID_;
}
BaseAction() [3/3]
BaseAction::BaseAction (const BaseAction * other_)
Definition at line 24 of file BaseAction.cpp.
{
     name = other_->ReturnName();
     discription = other_->ReturnDiscription();
     target = other_->ReturnTargetType();
     actionID = other_->ReturnActionID();
}
 BaseAction()
BaseAction::~BaseAction () [virtual]
Definition at line 87 of file BaseAction.cpp.
{
     OnDestroy();
}
Member Function Documentation
OnDestroy()
void BaseAction::OnDestroy ()
Definition at line 83 of file BaseAction.cpp.
{
     //The clean up method
}
Referenced by ~BaseAction().
ReturnActionID()
uint32 BaseAction::ReturnActionID () const
Definition at line 79 of file BaseAction.cpp.
{
     return actionID;
}
Referenced by AbilityAction::AbilityAction(), BaseAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
ReturnActionType()
ACTIONTYPE BaseAction::ReturnActionType () const
Definition at line 63 of file BaseAction.cpp.
{
     return action;
}
Referenced by AbilityAction::AbilityAction(), DamageDeltSystem::BaseCalculate(), CommandAction::CommandAction(), and ItemAction::ItemAction().
ReturnDiscription()
FString BaseAction::ReturnDiscription () const
Definition at line 59 of file BaseAction.cpp.
{
     return discription;
}
Referenced by AbilityAction::AbilityAction(), BaseAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
ReturnInteractionType()
INTERACTIONTYPE BaseAction::ReturnInteractionType () const
Definition at line 75 of file BaseAction.cpp.
{
     return interaction;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
ReturnName()
FString BaseAction::ReturnName () const
Referenced by AbilityAction::AbilityAction(), StatSheetObject::AddAbilityAction(), StatSheetObject::AddCommandAction(), StatSheetObject::AddEquipment(), StatSheetObject::AddItemAction(), BaseAction(), DamageDeltSystem::BaseCalculate(), CommandAction::CommandAction(), and ItemAction::ItemAction().
ReturnStatMap()
TMap< FString, float > BaseAction::ReturnStatMap () const
Definition at line 71 of file BaseAction.cpp.
{
     return statMap;
}
ReturnTargetType()
TARGETTYPE BaseAction::ReturnTargetType () const
Definition at line 67 of file BaseAction.cpp.
{
     return target;
}
Referenced by BaseAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetActionID()
void BaseAction::SetActionID (const uint32 actionID_)
Definition at line 51 of file BaseAction.cpp.
{
     actionID = actionID_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetActionType()
void BaseAction::SetActionType (const ACTIONTYPE type_)
Definition at line 39 of file BaseAction.cpp.
{
     action = type_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetDiscription()
void BaseAction::SetDiscription (const FString discription_)
Definition at line 35 of file BaseAction.cpp.
{
     discription = discription_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetInteractionType()
void BaseAction::SetInteractionType (const INTERACTIONTYPE type_)
Definition at line 47 of file BaseAction.cpp.
{
     interaction = type_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetName()
void BaseAction::SetName (const FString name_)
Definition at line 31 of file BaseAction.cpp.
{
     name = name_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().
SetTargetType()
void BaseAction::SetTargetType (const TARGETTYPE type_)
Definition at line 43 of file BaseAction.cpp.
{
     target = type_;
}
Referenced by AbilityAction::AbilityAction(), CommandAction::CommandAction(), and ItemAction::ItemAction().