EffectSystem Class Reference
#include <EffectSystem.h>
Public Member Functions
 EffectSystem ()=delete
 EffectSystem (const EffectSystem &)=delete
 EffectSystem (EffectSystem &&)=delete
 EffectSystem & operator= (const EffectSystem &)=delete
 EffectSystem & operator= (EffectSystem &&)=delete
 ~EffectSystem ()
Static Public Member Functions
static void Addtarget (StatSheetObject *target_)
Add target to the target array.
static void BaseCalculate (const bool IsSingleTarget_, BaseAction *const action_)
static void CallculateEffect (BaseAction *action_)
Calculates the effect
static void OnDestroy ()
static void RemoveEffect (BaseAction *action_)
Removes the effect by the action.
static void SetTarget (StatSheetObject *target_)
Sets target.
Static Private Attributes
static StatSheetObject * target = nullptr
static BaseAction * targetAction = nullptr
static TArray< StatSheetObject * > targets = TArray< StatSheetObject*>()
Detailed Description
Definition at line 8 of file EffectSystem.h.
Constructor & Destructor Documentation
EffectSystem() [1/3]
EffectSystem::EffectSystem (const EffectSystem &) [delete]
EffectSystem() [2/3]
EffectSystem::EffectSystem (EffectSystem &&) [delete]
EffectSystem() [3/3]
EffectSystem::EffectSystem () [delete]
~EffectSystem()
EffectSystem::~EffectSystem ()
Definition at line 363 of file EffectSystem.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
Addtarget()
void EffectSystem::Addtarget (StatSheetObject * target_) [static]
Add target to the target array.
Definition at line 341 of file EffectSystem.cpp.
{
    targets.Add(target_);
}
References targets.
BaseCalculate()
void EffectSystem::BaseCalculate (const bool IsSingleTarget_, BaseAction *const action_) [static]
Definition at line 15 of file EffectSystem.cpp.
{
    if (IsSingledTarget_)
    {
        if (target)
        {
            if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
            {
                ItemAction* item = dynamic_cast<ItemAction*>(action_);
                if (item->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL)
                {
                    //calculate for physical attributes
                    if (item->ReturnEffectList().Num() > 0)
                    {
                        for (auto ability : item->ReturnEffectList())
                        {
                            if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                            {
                                //Communicate with Damage System
                            }
                            else
                            {
                                Debugger::SetSeverity(MessageType::E_ERROR);
                                Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                return;
                            }
                        }
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                        return;
                    }
                }
                else if (item->ReturnInteractionType() == INTERACTIONTYPE::E_ABILITY)
                {
                    //calculate for ability attributes
                    if (item->ReturnEffectList().Num() > 0)
                    {
                        for (auto ability : item->ReturnEffectList())
                        {
                            if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                            {
                                //Communicate with Damage System
                            }
                            else
                            {
                                Debugger::SetSeverity(MessageType::E_ERROR);
                                Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                return;
                            }
                        }
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                        return;
                    }
                }
                else if (item->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL_AND_ABILITY)
                {
                    //calculate for physical and ability attributes
                    if (item->ReturnEffectList().Num() > 0)
                    {
                        for (auto ability : item->ReturnEffectList())
                        {
                            if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                            {
                                //Communicate with stat System
                            }
                            else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                            {
                                //Communicate with Damage System
                            }
                            else
                            {
                                Debugger::SetSeverity(MessageType::E_ERROR);
                                Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                return;
                            }
                        }
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                        return;
                    }
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error("No interaction fits the criteria.", "EffectSystem.cpp", __LINE__);
                    return;
                }
            }
            else if (action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
            {
                AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
                if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                {
                    //Communicate with stat System
                }
                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                {
                    //Communicate with stat System
                }
                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                {
                    //Communicate with Damage System
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                    return;
                }
            }
            else
            {
                Debugger::SetSeverity(MessageType::E_ERROR);
                Debugger::Error("action does not meet the effect criteria.", "EffectSystem.cpp", __LINE__);
                return;
            }
        }
        else
        {
            Debugger::SetSeverity(MessageType::E_ERROR);
            Debugger::Error("target was not set.", "EffectSystem.cpp", __LINE__);
            return;
        }
    }
    else if (!IsSingledTarget_)
    {
        if (targets.Num() > 0)
        {
            for (auto target : targets)
            {
                if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
                {
                    ItemAction* item = dynamic_cast<ItemAction*>(action_);
                    if (item->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL)
                    {
                        //calculate for physical attributes
                        if (item->ReturnEffectList().Num() > 0)
                        {
                            for (auto ability : item->ReturnEffectList())
                            {
                                if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                                {
                                    //Communicate with Damage System
                                }
                                else
                                {
                                    Debugger::SetSeverity(MessageType::E_ERROR);
                                    Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                    return;
                                }
                            }
                        }
                        else
                        {
                            Debugger::SetSeverity(MessageType::E_ERROR);
                            Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                            return;
                        }
                    }
                    else if (item->ReturnInteractionType() == INTERACTIONTYPE::E_ABILITY)
                    {
                        //calculate for ability attributes
                        if (item->ReturnEffectList().Num() > 0)
                        {
                            for (auto ability : item->ReturnEffectList())
                            {
                                if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                                {
                                    //Communicate with Damage System
                                }
                                else
                                {
                                    Debugger::SetSeverity(MessageType::E_ERROR);
                                    Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                    return;
                                }
                            }
                        }
                        else
                        {
                            Debugger::SetSeverity(MessageType::E_ERROR);
                            Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                            return;
                        }
                    }
                    else if (item->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL_AND_ABILITY)
                    {
                        //calculate for physical and ability attributes
                        if (item->ReturnEffectList().Num() > 0)
                        {
                            for (auto ability : item->ReturnEffectList())
                            {
                                if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                                {
                                    //Communicate with stat System
                                }
                                else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                                {
                                    //Communicate with Damage System
                                }
                                else
                                {
                                    Debugger::SetSeverity(MessageType::E_ERROR);
                                    Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                                    return;
                                }
                            }
                        }
                        else
                        {
                            Debugger::SetSeverity(MessageType::E_ERROR);
                            Debugger::Error("No ability found or is null.", "EffectSystem.cpp", __LINE__);
                            return;
                        }
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error("No interaction fits the criteria.", "EffectSystem.cpp", __LINE__);
                        return;
                    }
                }
                else if (action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
                {
                    AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
                    if (ability->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                    {
                        //Communicate with stat System
                    }
                    else if (ability->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                    {
                        //Communicate with stat System
                    }
                    else if (ability->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                    {
                        //Communicate with Damage System
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error("No ability type is found and cannot calculate.", "EffectSystem.cpp", __LINE__);
                        return;
                    }
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error("action does not meet the effect criteria.", "EffectSystem.cpp", __LINE__);
                    return;
                }
            }
        }
        else
        {
            Debugger::SetSeverity(MessageType::E_ERROR);
            Debugger::Error("target array is empty.", "EffectSystem.cpp", __LINE__);
            return;
        }
    }
    OnDestroy();
}
References E_ABILITY, E_DAMAGE_MODIFYER, E_ERROR, E_ITEM, E_MODIFIYER, E_PHYSICAL, E_PHYSICAL_AND_ABILITY, E_TMP_MODIFIYER, Debugger::Error(), OnDestroy(), AbilityAction::ReturnAbilityType(), BaseAction::ReturnActionType(), ItemAction::ReturnEffectList(), BaseAction::ReturnInteractionType(), Debugger::SetSeverity(), target, and targets.
CallculateEffect()
void EffectSystem::CallculateEffect (BaseAction * action_) [static]
Calculates the effect
Definition at line 329 of file EffectSystem.cpp.
{
    //This will extract the equation class and calculate the values needed.
}
OnDestroy()
void EffectSystem::OnDestroy () [static]
Definition at line 345 of file EffectSystem.cpp.
{
    //clear all variables.
    if (target)
    {
        delete target;
        target = nullptr;
    }
    if (targets.Num() > 0)
    {
        for(auto t : targets)
        {
            delete t;
            t = nullptr;
        }
        targets.Empty();
    }
}
References target, and targets.
operator=() [1/2]
 EffectSystem& EffectSystem::operator= (const EffectSystem &) [delete]
operator=() [2/2]
 EffectSystem& EffectSystem::operator= (EffectSystem &&) [delete]
RemoveEffect()
void EffectSystem::RemoveEffect (BaseAction * action_) [static]
Removes the effect by the action.
Definition at line 333 of file EffectSystem.cpp.
{
    //Same process as the equation and reverse calculate the value needed.
}
SetTarget()
void EffectSystem::SetTarget (StatSheetObject * target_) [static]
Sets target.
Definition at line 337 of file EffectSystem.cpp.
{
    target = target_;
}
References target.
Field Documentation
target
 StatSheetObject * EffectSystem::target = nullptr [static], [private]
Definition at line 11 of file EffectSystem.h.
targetAction
 BaseAction * EffectSystem::targetAction = nullptr [static], [private]
Definition at line 13 of file EffectSystem.h.
targets
TArray< StatSheetObject * > EffectSystem::targets = TArray< StatSheetObject*>() [static], [private]
Definition at line 12 of file EffectSystem.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ EffectSystem.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ EffectSystem.cpp