StatSheetObject Class Reference
#include <StatSheetObject.h>
Public Member Functions
void AddAbilityAction (AbilityAction *const ability_)
Adds a ability action to the ability map.
void AddCommandAction (CommandAction *const command_)
Adds a command action the command map.
void AddEquipment (ItemAction *const equipment_)
Adds a eqquipment-item action to the equipmnet map.
void AddItemAction (ItemAction *const item_)
Adds a item action to the item map.
void OnDestroy ()
void RemoveAbilityAction (const FString name_)
Removes a ability action if there is one in the map.
void RemoveCommandAction (const FString name_)
Removes a command action if there is one in the map.
void RemoveEquipment (const FString name_)
Removes a equipment-type action if there is one in the map.
void RemoveItemAction (const FString name_)
Removes a item action if there is one in the map.
 AbilityAction * ReturnAbility (const FString name_) const
Returns a ability action by its name from the ability map.
TMap< FString, AbilityAction * > ReturnAbilityMap () const
Returns the ability map.
 CommandAction * ReturnCommand (FString name_) const
Returns a command action by its name from the command map.
TMap< FString, CommandAction * > ReturnCommandMap () const
Returns the commmand map.
 ItemAction * ReturnEquipment (const FString name_) const
Returns a equipment-item action by its name from the equipment map.
TMap< FString, ItemAction * > ReturnEquipmentMap () const
Returns the equipment map.
 ItemAction * ReturnItem (const FString name_) const
Returns a item action by its name from the item map.
TMap< FString, ItemAction * > ReturnItemMap () const
Returns the item map.
FString ReturnName () const
Returns name.
TMap< FString, float > ReturnStatMap () const
Returns the statMap.
FString ReturnTag () const
Returns tag.
void SetName (const FString name_)
Sets name.
void SetTag (const FString tag_)
Sets tag.
 StatSheetObject ()
 StatSheetObject (const FString name_, const FString tag_, const TMap< FString, CommandAction * > commandMap_, const TMap< FString, ItemAction * > itemMap_, const TMap< FString, AbilityAction * > abilityMap_, const TMap< FString, float > statMap_, const TMap< FString, ItemAction * > equipmentMap_)
 StatSheetObject (StatSheetObject *const other_)
 ~StatSheetObject ()
Private Attributes
TMap< FString, AbilityAction * > abilityMap
TMap< FString, CommandAction * > commandMap
TMap< FString, ItemAction * > equipmentMap
TMap< FString, ItemAction * > itemMap
FString name
TMap< FString, float > statMap
FString tag
Detailed Description
Definition at line 14 of file StatSheetObject.h.
Constructor & Destructor Documentation
StatSheetObject() [1/3]
StatSheetObject::StatSheetObject ()
Definition at line 10 of file StatSheetObject.cpp.
                                 : commandMap(TMap<FString, CommandAction*>()), itemMap(TMap<FString, ItemAction*>()), abilityMap(TMap<FString, AbilityAction*>()), statMap(TMap<FString, float>()), equipmentMap(TMap<FString, ItemAction*>())
{
    name = "";
    tag = "";
}
References name, and tag.
StatSheetObject() [2/3]
StatSheetObject::StatSheetObject (const FString name_, const FString tag_, const TMap< FString, CommandAction * > commandMap_, const TMap< FString, ItemAction * > itemMap_, const TMap< FString, AbilityAction * > abilityMap_, const TMap< FString, float > statMap_, const TMap< FString, ItemAction * > equipmentMap_)
Definition at line 15 of file StatSheetObject.cpp.
{
    name = name_;
    tag = tag_;
    commandMap = commandMap_;
    itemMap = itemMap_;
    abilityMap = abilityMap_;
    equipmentMap = equipmentMap_;
}
References abilityMap, commandMap, equipmentMap, itemMap, name, and tag.
StatSheetObject() [3/3]
StatSheetObject::StatSheetObject (StatSheetObject *const other_)
Definition at line 24 of file StatSheetObject.cpp.
{
    name = other_->ReturnName();
    tag = other_->ReturnTag();
    commandMap = other_->ReturnCommandMap();
    itemMap = other_->ReturnItemMap();
    abilityMap = other_->ReturnAbilityMap();
    equipmentMap = other_->ReturnEquipmentMap();
    statMap = other_->ReturnStatMap();
}
References abilityMap, commandMap, equipmentMap, itemMap, name, ReturnAbilityMap(), ReturnCommandMap(), ReturnEquipmentMap(), ReturnItemMap(), ReturnName(), ReturnStatMap(), ReturnTag(), statMap, and tag.
~StatSheetObject()
StatSheetObject::~StatSheetObject ()
Definition at line 156 of file StatSheetObject.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
AddAbilityAction()
void StatSheetObject::AddAbilityAction (AbilityAction *const ability_)
Adds a ability action to the ability map.
Definition at line 59 of file StatSheetObject.cpp.
{
    abilityMap.Add(ability_->ReturnName(), ability_);
}
References abilityMap, and BaseAction::ReturnName().
AddCommandAction()
void StatSheetObject::AddCommandAction (CommandAction *const command_)
Adds a command action the command map.
Definition at line 51 of file StatSheetObject.cpp.
{
    commandMap.Add(command_->ReturnName(), command_);
}
References commandMap, and BaseAction::ReturnName().
AddEquipment()
void StatSheetObject::AddEquipment (ItemAction *const equipment_)
Adds a eqquipment-item action to the equipmnet map.
Definition at line 63 of file StatSheetObject.cpp.
{
    equipmentMap.Add(equipment_->ReturnName(), equipment_);
}
References equipmentMap, and BaseAction::ReturnName().
AddItemAction()
void StatSheetObject::AddItemAction (ItemAction *const item_)
Adds a item action to the item map.
Definition at line 55 of file StatSheetObject.cpp.
{
    itemMap.Add(item_->ReturnName(), item_);
}
References itemMap, and BaseAction::ReturnName().
OnDestroy()
void StatSheetObject::OnDestroy ()
Definition at line 144 of file StatSheetObject.cpp.
{
    //Clear out all pointer within the maps
    if (commandMap.Num() > 0)
    {
        for(auto command : commandMap)
        {
            delete command.Value;
        }
        commandMap.Empty();
    }
}
References commandMap.
RemoveAbilityAction()
void StatSheetObject::RemoveAbilityAction (const FString name_)
Removes a ability action if there is one in the map.
Definition at line 75 of file StatSheetObject.cpp.
{
    abilityMap.Remove(name_);
}
References abilityMap.
RemoveCommandAction()
void StatSheetObject::RemoveCommandAction (const FString name_)
Removes a command action if there is one in the map.
Definition at line 67 of file StatSheetObject.cpp.
{
    commandMap.Remove(name_);
}
References commandMap.
RemoveEquipment()
void StatSheetObject::RemoveEquipment (const FString name_)
Removes a equipment-type action if there is one in the map.
Definition at line 79 of file StatSheetObject.cpp.
{
    equipmentMap.Remove(name);
}
References equipmentMap, and name.
RemoveItemAction()
void StatSheetObject::RemoveItemAction (const FString name_)
Removes a item action if there is one in the map.
Definition at line 71 of file StatSheetObject.cpp.
{
    itemMap.Remove(name_);
}
References itemMap.
ReturnAbility()
 AbilityAction * StatSheetObject::ReturnAbility (const FString name_) const
Returns a ability action by its name from the ability map.
Definition at line 103 of file StatSheetObject.cpp.
{
    if (!abilityMap.Find(name_))
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error("Ability action " + name_ + " could not be found", "StatSheetObject.cpp", __LINE__);
        return nullptr;
    }
    
    return abilityMap[name_];
}
References abilityMap, E_ERROR, Debugger::Error(), and Debugger::SetSeverity().
ReturnAbilityMap()
TMap< FString, AbilityAction * > StatSheetObject::ReturnAbilityMap () const
Returns the ability map.
Definition at line 132 of file StatSheetObject.cpp.
{
    return abilityMap;
}
References abilityMap.
ReturnCommand()
 CommandAction * StatSheetObject::ReturnCommand (FString name_) const
Returns a command action by its name from the command map.
Definition at line 83 of file StatSheetObject.cpp.
{
    if (!commandMap.Find(name_))
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error("Command action " + name_ + " could not be found", "StatSheetObject.cpp", __LINE__);
        return nullptr;
    }
        return commandMap[name_];
}
References commandMap, E_ERROR, Debugger::Error(), and Debugger::SetSeverity().
ReturnCommandMap()
TMap< FString, CommandAction * > StatSheetObject::ReturnCommandMap () const
Returns the commmand map.
Definition at line 124 of file StatSheetObject.cpp.
{
    return commandMap;
}
References commandMap.
ReturnEquipment()
 ItemAction * StatSheetObject::ReturnEquipment (const FString name_) const
Returns a equipment-item action by its name from the equipment map.
Definition at line 114 of file StatSheetObject.cpp.
{
    if (!equipmentMap.Find(name_))
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error("Equipment action " + name_ + " could not be found", "StatSheetObject.cpp", __LINE__);
        return nullptr;
    }
        return equipmentMap[name_];
}
References E_ERROR, equipmentMap, Debugger::Error(), and Debugger::SetSeverity().
ReturnEquipmentMap()
TMap< FString, ItemAction * > StatSheetObject::ReturnEquipmentMap () const
Returns the equipment map.
Definition at line 140 of file StatSheetObject.cpp.
{
    return equipmentMap;
}
References equipmentMap.
ReturnItem()
 ItemAction * StatSheetObject::ReturnItem (const FString name_) const
Returns a item action by its name from the item map.
Definition at line 93 of file StatSheetObject.cpp.
{
    if (!itemMap.Find(name_))
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error("Item action " + name_ + " could not be found", "StatSheetObject.cpp", __LINE__);
        return nullptr;
    }
        return itemMap[name_];
}
References E_ERROR, Debugger::Error(), itemMap, and Debugger::SetSeverity().
ReturnItemMap()
TMap< FString, ItemAction * > StatSheetObject::ReturnItemMap () const
Returns the item map.
Definition at line 128 of file StatSheetObject.cpp.
{
    return itemMap;
}
References itemMap.
ReturnName()
FString StatSheetObject::ReturnName () const
Returns name.
Definition at line 43 of file StatSheetObject.cpp.
{
    return name;
}
References name.
ReturnStatMap()
TMap< FString, float > StatSheetObject::ReturnStatMap () const
Returns the statMap.
Definition at line 136 of file StatSheetObject.cpp.
{
    return statMap;
}
References statMap.
ReturnTag()
FString StatSheetObject::ReturnTag () const
Returns tag.
Definition at line 47 of file StatSheetObject.cpp.
{
    return tag;
}
References tag.
SetName()
void StatSheetObject::SetName (const FString name_)
Sets name.
Definition at line 35 of file StatSheetObject.cpp.
{
    name = name_;
}
References name.
SetTag()
void StatSheetObject::SetTag (const FString tag_)
Sets tag.
Definition at line 39 of file StatSheetObject.cpp.
{
    tag = tag_;
}
References tag.
Field Documentation
abilityMap
TMap<FString, AbilityAction*> StatSheetObject::abilityMap [private]
Definition at line 21 of file StatSheetObject.h.
commandMap
TMap<FString, CommandAction*> StatSheetObject::commandMap [private]
Definition at line 19 of file StatSheetObject.h.
equipmentMap
TMap<FString, ItemAction*> StatSheetObject::equipmentMap [private]
Definition at line 23 of file StatSheetObject.h.
itemMap
TMap<FString, ItemAction*> StatSheetObject::itemMap [private]
Definition at line 20 of file StatSheetObject.h.
name
FString StatSheetObject::name [private]
Definition at line 17 of file StatSheetObject.h.
statMap
TMap<FString, float> StatSheetObject::statMap [private]
Definition at line 22 of file StatSheetObject.h.
tag
FString StatSheetObject::tag [private]
Definition at line 18 of file StatSheetObject.h.
The documentation for this class was generated from the following files:
Battle_Box/Private/ StatSheetObject.h
Battle_Box/Private/ StatSheetObject.cpp