BaseAction Class Reference
#include <BaseAction.h>
Public Member Functions
 BaseAction ()
 BaseAction (const BaseAction *other_)
 BaseAction (FString name_, FString discription_, ACTIONTYPE action_, TARGETTYPE target_, INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_)
Base Construction.
void OnDestroy ()
uint32 ReturnActionID () const
Return Action ID.
 ACTIONTYPE ReturnActionType () const
Return action type.
FString ReturnDiscription () const
Return discription.
 INTERACTIONTYPE ReturnInteractionType () const
Return Interaction type.
FString ReturnName () const
Return Name.
 TARGETTYPE ReturnTargetType () const
Return target type.
void SetActionID (const uint32 actionID_)
Sets action ID.
void SetActionType (const ACTIONTYPE type_)
Sets Actiontype.
void SetDiscription (const FString discription_)
Sets Discription.
void SetInteractionType (const INTERACTIONTYPE type_)
Sets interaction type.
void SetName (const FString name_)
Sets Name.
void SetTargetType (const TARGETTYPE type_)
Sets target type.
virtual ~BaseAction ()
Private Attributes
 ACTIONTYPE action
uint32 actionID
FString discription
 INTERACTIONTYPE interaction
FString name
 TARGETTYPE target
Detailed Description
Definition at line 62 of file BaseAction.h.
Constructor & Destructor Documentation
BaseAction() [1/3]
BaseAction::BaseAction ()
Definition at line 6 of file BaseAction.cpp.
{
    name = "";
    discription = "";
    action = ACTIONTYPE::E_NONE;
    target = TARGETTYPE::E_NONE;
    interaction = INTERACTIONTYPE::E_NONE;
    actionID = 00;
}
References action, actionID, discription, E_NONE, interaction, name, and target.
BaseAction() [2/3]
BaseAction::BaseAction (FString name_, FString discription_, ACTIONTYPE action_, TARGETTYPE target_, INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_)
Base Construction.
Definition at line 15 of file BaseAction.cpp.
{
    name = name_;
    discription = discription_;
    action = action_;
    target = target_;
    interaction = interaction_;
    actionID = actionID_;
}
References action, actionID, discription, interaction, name, and target.
BaseAction() [3/3]
BaseAction::BaseAction (const BaseAction * other_)
Definition at line 24 of file BaseAction.cpp.
{
    name = other_->ReturnName();
    discription = other_->ReturnDiscription();
    target = other_->ReturnTargetType();
    actionID = other_->ReturnActionID();
}
References actionID, discription, name, ReturnActionID(), ReturnDiscription(), ReturnName(), ReturnTargetType(), and target.
~BaseAction()
BaseAction::~BaseAction () [virtual]
Definition at line 83 of file BaseAction.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
OnDestroy()
void BaseAction::OnDestroy ()
Definition at line 79 of file BaseAction.cpp.
{
    //The clean up method
}
ReturnActionID()
uint32 BaseAction::ReturnActionID () const
Return Action ID.
Definition at line 75 of file BaseAction.cpp.
{
    return actionID;
}
References actionID.
ReturnActionType()
 ACTIONTYPE BaseAction::ReturnActionType () const
Return action type.
Definition at line 63 of file BaseAction.cpp.
{
    return action;
}
References action.
ReturnDiscription()
FString BaseAction::ReturnDiscription () const
Return discription.
Definition at line 59 of file BaseAction.cpp.
{
    return discription;
}
References discription.
ReturnInteractionType()
 INTERACTIONTYPE BaseAction::ReturnInteractionType () const
Return Interaction type.
Definition at line 71 of file BaseAction.cpp.
{
    return interaction;
}
References interaction.
ReturnName()
FString BaseAction::ReturnName () const
Return Name.
ReturnTargetType()
 TARGETTYPE BaseAction::ReturnTargetType () const
Return target type.
Definition at line 67 of file BaseAction.cpp.
{
    return target;
}
References target.
SetActionID()
void BaseAction::SetActionID (const uint32 actionID_)
Sets action ID.
Definition at line 51 of file BaseAction.cpp.
{
    actionID = actionID_;
}
References actionID.
SetActionType()
void BaseAction::SetActionType (const ACTIONTYPE type_)
Sets Actiontype.
Definition at line 39 of file BaseAction.cpp.
{
    action = type_;
}
References action.
SetDiscription()
void BaseAction::SetDiscription (const FString discription_)
Sets Discription.
Definition at line 35 of file BaseAction.cpp.
{
    discription = discription_;
}
References discription.
SetInteractionType()
void BaseAction::SetInteractionType (const INTERACTIONTYPE type_)
Sets interaction type.
Definition at line 47 of file BaseAction.cpp.
{
    interaction = type_;
}
References interaction.
SetName()
void BaseAction::SetName (const FString name_)
Sets Name.
Definition at line 31 of file BaseAction.cpp.
{
    name = name_;
}
References name.
SetTargetType()
void BaseAction::SetTargetType (const TARGETTYPE type_)
Sets target type.
Definition at line 43 of file BaseAction.cpp.
{
    target = type_;
}
References target.
Field Documentation
action
 ACTIONTYPE BaseAction::action [private]
Definition at line 67 of file BaseAction.h.
actionID
uint32 BaseAction::actionID [private]
Definition at line 70 of file BaseAction.h.
discription
FString BaseAction::discription [private]
Definition at line 66 of file BaseAction.h.
interaction
 INTERACTIONTYPE BaseAction::interaction [private]
Definition at line 69 of file BaseAction.h.
name
FString BaseAction::name [private]
Definition at line 65 of file BaseAction.h.
target
 TARGETTYPE BaseAction::target [private]
Definition at line 68 of file BaseAction.h.
The documentation for this class was generated from the following files:
Battle_Box/Private/ActionClasses/ BaseAction.h
Battle_Box/Private/ActionClasses/ BaseAction.cpp