Equation Class Reference
#include <Equation.h>
Public Member Functions
float DetermineEquation (EQUATION_TYPE equationType_, float input_)
 Equation ()
 Equation (Equation &const other_)
 Equation (float scalar_, float rise_, float run_, float xIntercept_)
float GetDamageMultiplier () const
float GetDamageReducer () const
float ReturnGenrealScale () const
float ReturnRise () const
float ReturnRun () const
float ReturnXIntercept () const
void SetDamageMultiplier (float x_)
void SetDamageReducer (float x_)
 ~Equation ()
Private Member Functions
float Cosine (float input_)
float Div (float input_)
float Exponential (float input_)
float Linear (float input_)
float Quadratic (float input_)
float Sine (float input_)
Private Attributes
float damageMultipier = 1.5f
float damageReducer = 1.5f
float generalScalar
float rise
float run
float xIntercept
Detailed Description
Definition at line 25 of file Equation.h.
Constructor & Destructor Documentation
Equation() [1/3]
Equation::Equation ()
Definition at line 9 of file Equation.cpp.
{
generalScalar = 2.0f;
rise = 1.0f;
run = 2.0f;
xIntercept = 3.0f;
}
References generalScalar, rise, run, and xIntercept.
Equation() [2/3]
Equation::Equation (float scalar_, float rise_, float run_, float xIntercept_)
Definition at line 17 of file Equation.cpp.
{
    generalScalar = scalar_;
    rise = rise_;
    run = run_;
    xIntercept = xIntercept_;
}
References generalScalar, rise, run, and xIntercept.
Equation() [3/3]
Equation::Equation (Equation &const other_)
Definition at line 24 of file Equation.cpp.
{
    generalScalar = other_.ReturnGenrealScale();
    rise = other_.ReturnRise();
    run = other_.ReturnRun();
    xIntercept = other_.ReturnXIntercept();
}
References generalScalar, ReturnGenrealScale(), ReturnRise(), ReturnRun(), ReturnXIntercept(), rise, run, and xIntercept.
~Equation()
Equation::~Equation ()
Definition at line 31 of file Equation.cpp.
{
}
Member Function Documentation
Cosine()
float Equation::Cosine (float input_) [private]
Definition at line 107 of file Equation.cpp.
{
    float f = FMath::Cos(input_);
    return f;
}
DetermineEquation()
float Equation::DetermineEquation (EQUATION_TYPE equationType_, float input_)
Definition at line 50 of file Equation.cpp.
{
    float foo; // foo is the final number from each equation
    switch (equationType_)
    {
    case EQUATION_TYPE::E_EXPONENT:
        foo = Exponential(input_);
        return foo;
    case EQUATION_TYPE::E_LINEAR:
        foo = Linear(input_);
        return foo;
    case EQUATION_TYPE::E_QUADRADIC:
        foo = Quadratic(input_);
        return foo;
    case EQUATION_TYPE::E_DIV:
        foo = Div(input_);
        return foo;
    case EQUATION_TYPE::E_SINE:
        foo = Sine(input_);
        return foo;
    case EQUATION_TYPE::E_COSINE:
        foo = Cosine(input_);
        return foo;
    default:
        Debugger::Error("Equation type not valid", "Equation.cpp", __LINE__);
        break;
    }
    return 0.0f;
}
References Cosine(), Div(), E_COSINE, E_DIV, E_EXPONENT, E_LINEAR, E_QUADRADIC, E_SINE, Debugger::Error(), Exponential(), Linear(), Quadratic(), and Sine().
Div()
float Equation::Div (float input_) [private]
Definition at line 91 of file Equation.cpp.
{
    if (input_ == 0.0f) {
        Debugger::Warrning("Input is 0", "Equation.cpp", __LINE__);
    }
    float f = input_ / 2;
    return f;
}
References Debugger::Warrning().
Exponential()
float Equation::Exponential (float input_) [private]
Definition at line 80 of file Equation.cpp.
{
    //x is the constant
    //fx = ab^x
    if (input_ == 0.0f) {
        Debugger::Warrning("Input is 0", "Equation.cpp", __LINE__);
    }
    float f = FMath::Pow(generalScalar, input_) + rise;
    return f;
}
References generalScalar, rise, and Debugger::Warrning().
GetDamageMultiplier()
float Equation::GetDamageMultiplier () const
Definition at line 126 of file Equation.cpp.
{
    return damageMultipier;
}
References damageMultipier.
GetDamageReducer()
float Equation::GetDamageReducer () const
Definition at line 136 of file Equation.cpp.
{
    return damageReducer;
}
References damageReducer.
Linear()
float Equation::Linear (float input_) [private]
Definition at line 113 of file Equation.cpp.
{
    float f = run * input_ + (rise);
    return f;
}
References rise, and run.
Quadratic()
float Equation::Quadratic (float input_) [private]
Definition at line 119 of file Equation.cpp.
{
    // y = x^2 + x*b + c;
    float y = FMath::Pow(input_, 2.0f); + (xIntercept * input_) + rise;
    return y;
}
References rise, and xIntercept.
ReturnGenrealScale()
float Equation::ReturnGenrealScale () const
Definition at line 34 of file Equation.cpp.
{
    return generalScalar;
}
References generalScalar.
ReturnRise()
float Equation::ReturnRise () const
Definition at line 38 of file Equation.cpp.
{
    return rise;
}
References rise.
ReturnRun()
float Equation::ReturnRun () const
Definition at line 42 of file Equation.cpp.
{
    return run;
}
References run.
ReturnXIntercept()
float Equation::ReturnXIntercept () const
Definition at line 46 of file Equation.cpp.
{
    return xIntercept;
}
References xIntercept.
SetDamageMultiplier()
void Equation::SetDamageMultiplier (float x_)
Definition at line 131 of file Equation.cpp.
{
    damageMultipier = x_;
}
References damageMultipier.
SetDamageReducer()
void Equation::SetDamageReducer (float x_)
Definition at line 141 of file Equation.cpp.
{
    damageReducer = x_;
}
References damageReducer.
Sine()
float Equation::Sine (float input_) [private]
Definition at line 101 of file Equation.cpp.
{
    float f = FMath::Sin(input_);
    return f;
}
Field Documentation
damageMultipier
float Equation::damageMultipier = 1.5f [private]
Definition at line 44 of file Equation.h.
damageReducer
float Equation::damageReducer = 1.5f [private]
Definition at line 45 of file Equation.h.
generalScalar
float Equation::generalScalar [private]
Definition at line 46 of file Equation.h.
rise
float Equation::rise [private]
Definition at line 46 of file Equation.h.
run
float Equation::run [private]
Definition at line 46 of file Equation.h.
xIntercept
float Equation::xIntercept [private]
Definition at line 46 of file Equation.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Public/ Equation.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ Equation.cpp