DamageDeltSystem Class Reference
#include <DamageDeltSystem.h>
Public Member Functions
 DamageDeltSystem ()=delete
 DamageDeltSystem (const DamageDeltSystem &)=delete
 DamageDeltSystem (DamageDeltSystem &&)=delete
 DamageDeltSystem & operator= (const DamageDeltSystem &)=delete
 DamageDeltSystem & operator= (DamageDeltSystem &&)=delete
 ~DamageDeltSystem ()
Static Public Member Functions
static void AddTargetToArray (StatSheetObject *const target_)
Adds another target to the array.
static void CalculateDamage (const bool IsSingledTarget_, BaseAction *const action_)
Static moethod for the base function.
static void OnDestroy ()
static const TArray< float > ReturnDamageValues ()
Returns the damage value array.
static const float ReturnTotalDamageValue ()
Returns the damage value.
static void SetOwner (StatSheetObject *const owner_)
Sets who the owner of the damage.
static void SetTarget (StatSheetObject *const target_)
Sets the target who is being damaged.
Static Private Member Functions
static void BaseCalculate (const bool IsSingledTarget_, BaseAction *const action_)
System calculation.
static float CalculateAbilityDamage (AbilityAction *const targetAbility_)
Calculates the damage of a ability item.
static float CalculateItemDamage (ItemAction *const targetItem_)
Calculates the damage of an item.
static float CalculateMagicalDefence (StatSheetObject *const target_)
Calculates the magical defence of the target.
static float CalculatePhysicalDefence (StatSheetObject *const target_)
Calculates the physical defence of the target.
static float CalculateWeaponDamage (ItemAction *const target_)
Claculates the damage of a weapon item.
Static Private Attributes
static StatSheetObject * owner = nullptr
static StatSheetObject * singleTarget = nullptr
static TArray< StatSheetObject * > targets = TArray< StatSheetObject*>()
static float totalDamageValue = 0.0f
static TArray< float > totalDamageValues = TArray<float>()
Detailed Description
Definition at line 12 of file DamageDeltSystem.h.
Constructor & Destructor Documentation
DamageDeltSystem() [1/3]
DamageDeltSystem::DamageDeltSystem (const DamageDeltSystem &) [delete]
DamageDeltSystem() [2/3]
DamageDeltSystem::DamageDeltSystem (DamageDeltSystem &&) [delete]
DamageDeltSystem() [3/3]
DamageDeltSystem::DamageDeltSystem () [delete]
~DamageDeltSystem()
DamageDeltSystem::~DamageDeltSystem ()
Definition at line 319 of file DamageDeltSystem.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
AddTargetToArray()
void DamageDeltSystem::AddTargetToArray (StatSheetObject *const target_) [static]
Adds another target to the array.
Definition at line 275 of file DamageDeltSystem.cpp.
{
    targets.Add(target_);
}
References targets.
BaseCalculate()
void DamageDeltSystem::BaseCalculate (const bool IsSingledTarget_, BaseAction *const action_) [static], [private], [virtual]
System calculation.
Implements BaseSystem .
Definition at line 16 of file DamageDeltSystem.cpp.
{
    if(IsSingledTarget_)
    {
        if (singleTarget == nullptr)
        {
            //This will claculate any damage for a single target.
            switch (action_->ReturnActionType())
            {
            case ACTIONTYPE::E_COMMAND:
                //Command will do basic act with basic stats
                //TO DO: Check if there is any damage in this command.
                CommandAction* command = dynamic_cast<CommandAction*>(action_);
                break;
            case ACTIONTYPE::E_ITEM:
                //Item will be sorted to what type then calculated for total damage.
                ItemAction* item = dynamic_cast<ItemAction*>(action_);
                if (item->ReturnItemType() == ITEMTYPE::E_CONSUMABLE)
                {
                    totalDamageValue = CalculateItemDamage(item) - CalculateMagicalDefence(singleTarget) + CalculatePhysicalDefence(singleTarget);
                }
                else if (item->ReturnItemType() == ITEMTYPE::E_WEAPON)
                {
                    totalDamageValue = CalculateItemDamage(item) - CalculateMagicalDefence(singleTarget) + CalculatePhysicalDefence(singleTarget);
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error("No Item to contain damage from: " + item->ReturnName(), "DamageDeltSystem.cpp", __LINE__);
                    return;
                }
                break;
            case ACTIONTYPE::E_ABILITY:
                //ability will retreive the damage value if any.
                //TO DO: create an enum for what type of ability it is.
                AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
                CalculateAbilityDamage(ability);
                break;
            }
            //TO DO: modify targets HP on stat system.
            StatSystem::ModifiyStat(singleTarget, totalDamageValue, "HP");
        }
        else
        {
            Debugger::SetSeverity(MessageType::E_ERROR);
            Debugger::Error("Target not avalable. Please set target if null", "DamageDeltSystem.cpp", __LINE__);
            return;
        }
    }
    else if (!IsSingledTarget_)
    {
        if (targets.Num > 0)
        {
            //This will calculate any damage for multiple targets.
            switch (action_->ReturnActionType())
            {
            case ACTIONTYPE::E_COMMAND:
                //Command will do basic act with basic stats
                //TO DO: Check if there is any damage in this command.
                CommandAction* command = dynamic_cast<CommandAction*>(action_);
                break;
            case ACTIONTYPE::E_ITEM:
                //Item will be sorted to what type then calculated for total damage.
                ItemAction* item = dynamic_cast<ItemAction*>(action_);
                if (item->ReturnItemType() == ITEMTYPE::E_CONSUMABLE)
                {
                    for (int i = 0; i < targets.Num(); i++)
                    {
                        totalDamageValues.Add(CalculateItemDamage(item) - CalculateMagicalDefence(targets[i]) + CalculatePhysicalDefence(targets[i]));
                    }
                }
                else if (item->ReturnItemType() == ITEMTYPE::E_WEAPON)
                {
                    for (int i = 0; i < targets.Num(); i++)
                    {
                        totalDamageValues.Add(CalculateItemDamage(item) - CalculateMagicalDefence(targets[i]) + CalculatePhysicalDefence(targets[i]));
                    }
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error("No Item to contain damage from: " + item->ReturnName(), "DamageDeltSystem.cpp", __LINE__);
                    return;
                }
                break;
            case ACTIONTYPE::E_ABILITY:
                //ability will retreive the damage value if any.
                //TO DO: create an enum for what type of ability it is.
                AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
                CalculateAbilityDamage(ability);
                break;
            }
            //TO DO: Modify stats of HP in targets.
            for (int i = 0; i < targets.Num; i++)
            {
                StatSystem::ModifiyStat(targets[i], totalDamageValues[i], "HP");
            }
        }
        else
        {
            Debugger::SetSeverity(MessageType::E_ERROR);
            Debugger::Error("No targets avalable it the array. Please insert a target before calculating.", "DamageDeltSystem.cpp", __LINE__);
            return;
        }
    }
    //TO DO: After modification is done empty all information.
    OnDestroy();
}
References CalculateAbilityDamage(), CalculateItemDamage(), CalculateMagicalDefence(), CalculatePhysicalDefence(), E_ABILITY, E_COMMAND, E_CONSUMABLE, E_ERROR, E_ITEM, E_WEAPON, Debugger::Error(), StatSystem::ModifiyStat(), OnDestroy(), BaseAction::ReturnActionType(), ItemAction::ReturnItemType(), BaseAction::ReturnName(), Debugger::SetSeverity(), singleTarget, targets, totalDamageValue, and totalDamageValues.
CalculateAbilityDamage()
float DamageDeltSystem::CalculateAbilityDamage (AbilityAction *const targetAbility_) [static], [private]
Calculates the damage of a ability item.
Definition at line 146 of file DamageDeltSystem.cpp.
{
    //Get the target action and get the damage value;
    return;
    /*if (targetAbility_->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL)
    {
        target
    }
    if (targetAbility_->ReturnInteractionType() == INTERACTIONTYPE::E_ABILITY)
    {
    }
    if(targetAbility_->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL_AND_ABILITY)
    {
    }*/
}
CalculateDamage()
void DamageDeltSystem::CalculateDamage (const bool IsSingledTarget_, BaseAction *const action_) [static]
Static moethod for the base function.
Definition at line 126 of file DamageDeltSystem.cpp.
{
    BaseCalculate(IsSingledTarget_, action_);
}
References BaseCalculate().
CalculateItemDamage()
float DamageDeltSystem::CalculateItemDamage (ItemAction *const targetItem_) [static], [private]
Calculates the damage of an item.
Definition at line 163 of file DamageDeltSystem.cpp.
{
    //Get the target and get the damage Value;
    if (targetItem_->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL)
    {
        return targetItem_->ReturnStatMap()["Atk"];
    }
    if (targetItem_->ReturnInteractionType() == INTERACTIONTYPE::E_ABILITY)
    {
        return targetItem_->ReturnStatMap()["M_Atk"];
    }
    if (targetItem_->ReturnInteractionType() ==INTERACTIONTYPE::E_PHYSICAL_AND_ABILITY)
    {
        return targetItem_->ReturnStatMap()["Atk"] + targetItem_->ReturnStatMap()["M_Atk"];
    }
    //switch (targetItem_->ReturnDamageType())
    //{
    //case DAMAGETYPE::E_HP_DAMAGE:
    // //This will get the damage from the stat map
    // return targetItem_->ReturnStatMap()["Atk"];
    //case DAMAGETYPE::E_HP_RECOVER:
    // return targetItem_->ReturnStatMap()["HP_REC"];
    //case DAMAGETYPE::E_MP_DAMAGE:
    // return targetItem_->ReturnStatMap()["M_Atk"];
    //case DAMAGETYPE::E_MP_RECOVER:
    // return targetItem_->ReturnStatMap()["M_REC"];
    //}
}
References E_ABILITY, E_PHYSICAL, E_PHYSICAL_AND_ABILITY, BaseAction::ReturnInteractionType(), and ItemAction::ReturnStatMap().
CalculateMagicalDefence()
float DamageDeltSystem::CalculateMagicalDefence (StatSheetObject *const target_) [static], [private]
Calculates the magical defence of the target.
Definition at line 229 of file DamageDeltSystem.cpp.
{
    float magicDefence = 0.0f;
    if (target_->ReturnEquipmentMap().Contains("Helment"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Helment"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Chest_Armor"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Chest_Armor"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Leg_Armor"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Leg_Armor"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Boots"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Boots"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Accessory_1"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Accessory_1"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Accesory_2"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Accesory_2"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Weapon_1"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Weapon_1"]->ReturnStatMap()["M_Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Weapon_2"))
    {
        magicDefence += target_->ReturnEquipmentMap()["Weapon_2"]->ReturnStatMap()["M_Def"];
    }
    magicDefence += target_->ReturnStatMap()["M_Def"];
    return magicDefence;
}
References StatSheetObject::ReturnEquipmentMap(), and StatSheetObject::ReturnStatMap().
CalculatePhysicalDefence()
float DamageDeltSystem::CalculatePhysicalDefence (StatSheetObject *const target_) [static], [private]
Calculates the physical defence of the target.
Definition at line 191 of file DamageDeltSystem.cpp.
{
    float physicalDefence = 0.0f;
    if(target_->ReturnEquipmentMap().Contains("Helment"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Helment"]->ReturnStatMap()["Def"];
    }
    if(target_->ReturnEquipmentMap().Contains("Chest_Armor"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Chest_Armor"]->ReturnStatMap()["Def"];
    }
    if(target_->ReturnEquipmentMap().Contains("Leg_Armor"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Leg_Armor"]->ReturnStatMap()["Def"];
    }
    if(target_->ReturnEquipmentMap().Contains("Boots"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Boots"]->ReturnStatMap()["Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Accessory_1"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Accessory_1"]->ReturnStatMap()["Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Accesory_2"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Accesory_2"]->ReturnStatMap()["Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Weapon_1"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Weapon_1"]->ReturnStatMap()["Def"];
    }
    if (target_->ReturnEquipmentMap().Contains("Weapon_2"))
    {
        physicalDefence += target_->ReturnEquipmentMap()["Weapon_2"]->ReturnStatMap()["Def"];
    }
    physicalDefence += target_->ReturnStatMap()["Def"];
    return physicalDefence;
}
References StatSheetObject::ReturnEquipmentMap(), and StatSheetObject::ReturnStatMap().
CalculateWeaponDamage()
float DamageDeltSystem::CalculateWeaponDamage (ItemAction *const target_) [static], [private]
Claculates the damage of a weapon item.
Definition at line 130 of file DamageDeltSystem.cpp.
{
    //This will return either magic, physical or both as a damage value;
    if (targetWeapon_->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL)
    {
        return targetWeapon_->ReturnStatMap()["Atk"];
    }
    if (targetWeapon_->ReturnInteractionType() == INTERACTIONTYPE::E_ABILITY)
    {
        return targetWeapon_->ReturnStatMap()["M_Atk"];
    }
    if (targetWeapon_->ReturnInteractionType() == INTERACTIONTYPE::E_PHYSICAL_AND_ABILITY)
    {
        return targetWeapon_->ReturnStatMap()["Atk"] + targetWeapon_->ReturnStatMap()["M_Atk"];
    }
}
References E_ABILITY, E_PHYSICAL, E_PHYSICAL_AND_ABILITY, BaseAction::ReturnInteractionType(), and ItemAction::ReturnStatMap().
OnDestroy()
void DamageDeltSystem::OnDestroy () [static]
Definition at line 279 of file DamageDeltSystem.cpp.
{
    //clean up any pointers
    if(singleTarget)
    {
        delete singleTarget;
        singleTarget = nullptr;
    }
    if(owner)
    {
        delete owner;
        owner = nullptr;
    }
    if(targets.Num() > 0)
    {
        for(auto& elem : targets)
        {
            delete elem;
            elem = nullptr;
        }
        targets.Empty();
    }
    totalDamageValue = 0.0f;
    if (totalDamageValues.Num > 0)
    {
        for (auto n : totalDamageValues)
        {
            n = 0.0f;
        }
        targets.Empty();
    }
}
References owner, singleTarget, targets, totalDamageValue, and totalDamageValues.
operator=() [1/2]
 DamageDeltSystem& DamageDeltSystem::operator= (const DamageDeltSystem &) [delete]
operator=() [2/2]
 DamageDeltSystem& DamageDeltSystem::operator= (DamageDeltSystem &&) [delete]
ReturnDamageValues()
const TArray< float > DamageDeltSystem::ReturnDamageValues () [static]
Returns the damage value array.
Definition at line 315 of file DamageDeltSystem.cpp.
{
    return totalDamageValues;
}
References totalDamageValues.
ReturnTotalDamageValue()
const float DamageDeltSystem::ReturnTotalDamageValue () [static]
Returns the damage value.
Definition at line 311 of file DamageDeltSystem.cpp.
{
    return totalDamageValue;
}
References totalDamageValue.
SetOwner()
void DamageDeltSystem::SetOwner (StatSheetObject *const owner_) [static]
Sets who the owner of the damage.
Definition at line 267 of file DamageDeltSystem.cpp.
{
    owner = owner_;
}
References owner.
SetTarget()
void DamageDeltSystem::SetTarget (StatSheetObject *const target_) [static]
Sets the target who is being damaged.
Definition at line 271 of file DamageDeltSystem.cpp.
{
    singleTarget = target_;
}
References singleTarget.
Field Documentation
owner
 StatSheetObject * DamageDeltSystem::owner = nullptr [static], [private]
Definition at line 16 of file DamageDeltSystem.h.
singleTarget
 StatSheetObject * DamageDeltSystem::singleTarget = nullptr [static], [private]
Definition at line 15 of file DamageDeltSystem.h.
targets
TArray< StatSheetObject * > DamageDeltSystem::targets = TArray< StatSheetObject*>() [static], [private]
Definition at line 17 of file DamageDeltSystem.h.
totalDamageValue
float DamageDeltSystem::totalDamageValue = 0.0f [static], [private]
Definition at line 18 of file DamageDeltSystem.h.
totalDamageValues
TArray< float > DamageDeltSystem::totalDamageValues = TArray<float>() [static], [private]
Definition at line 19 of file DamageDeltSystem.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ DamageDeltSystem.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ DamageDeltSystem.cpp