FBattle_BoxModule Class Reference
#include <Battle_Box.h>
Public Member Functions
virtual void ShutdownModule () override
virtual void StartupModule () override
IModuleInterface implementation.
Detailed Description
Definition at line 8 of file Battle_Box.h.
Member Function Documentation
ShutdownModule()
void FBattle_BoxModule::ShutdownModule () [override], [virtual]
Definition at line 30 of file Battle_Box.cpp.
{
    // This function may be called during shutdown to clean up your module. For modules that support dynamic reloading,
    // we call this function before unloading the module.
}
StartupModule()
void FBattle_BoxModule::StartupModule () [override], [virtual]
IModuleInterface implementation.
Definition at line 10 of file Battle_Box.cpp.
{
    // This code will execute after your module is loaded into memory; the exact timing is specified in the .uplugin file per-module
    Debugger::InitDebug();
    Debugger::SetSeverity(MessageType::E_INFO);
    if (BattleBoxFileManager::VerifyOnCreateDirectory(FPaths::ProjectPluginsDir() + "/Battle_Box/FileResource") &&
        BattleBoxFileManager::VerifyOnCreateDirectory(FPaths::ProjectPluginsDir() + "/Battle_Box/FileResource/StatSheets") &&
        BattleBoxFileManager::VerifyOnCreateDirectory(FPaths::ProjectPluginsDir() + "/Battle_Box/FileResource/ActionSheets"))
    {
        Debugger::SetSeverity(MessageType::E_INFO);
        Debugger::Info("All Directories are made!", "Battle_Box.cpp", __LINE__);
    }
    else
    {
        Debugger::SetSeverity(MessageType::E_INFO);
        Debugger::Error("A Directoy was not made!", "Battle_Box.cpp", __LINE__);
    }
}
References E_INFO, Debugger::Error(), Debugger::Info(), Debugger::InitDebug(), Debugger::SetSeverity(), and BattleBoxFileManager::VerifyOnCreateDirectory().
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Public/ Battle_Box.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ Battle_Box.cpp