AbilityAction Class Reference
#include <AbilityAction.h>
Public Member Functions
 AbilityAction ()
 AbilityAction (AbilityAction *const other_)
 AbilityAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const float duration_, ABILITYTYPE type_)
void OnDestroy ()
 ABILITYTYPE ReturnAbilityType () const
uint32 ReturnActionID () const
Return Action ID.
 ACTIONTYPE ReturnActionType () const
Return action type.
FString ReturnDiscription () const
Return discription.
float ReturnDuration () const
 INTERACTIONTYPE ReturnInteractionType () const
Return Interaction type.
TMap< FString, float > ReturnModStatMap ()
FString ReturnName () const
Return Name.
 TARGETTYPE ReturnTargetType () const
Return target type.
void SetAbilityType (const ABILITYTYPE type_)
void SetActionID (const uint32 actionID_)
Sets action ID.
void SetActionType (const ACTIONTYPE type_)
Sets Actiontype.
void SetDiscription (const FString discription_)
Sets Discription.
void SetDuration (const float duration_)
void SetInteractionType (const INTERACTIONTYPE type_)
Sets interaction type.
void SetName (const FString name_)
Sets Name.
void SetTargetType (const TARGETTYPE type_)
Sets target type.
 ~AbilityAction ()
Private Member Functions
float CalculateAbilityValue ()
Private Attributes
 ABILITYTYPE abilityType
float abilityValue
 ACTIONTYPE action
uint32 actionID
FString discription
float duration
 INTERACTIONTYPE interaction
TMap< FString, float > modStatMap
FString name
 TARGETTYPE target
Detailed Description
Definition at line 10 of file AbilityAction.h.
Constructor & Destructor Documentation
AbilityAction() [1/3]
AbilityAction::AbilityAction ()
Definition at line 4 of file AbilityAction.cpp.
{
    SetName("");
    SetDiscription("");
    SetActionType(ACTIONTYPE::E_NONE);
    SetTargetType(TARGETTYPE::E_NONE);
    SetInteractionType(INTERACTIONTYPE::E_NONE);
    SetActionID(00);
    duration = 0.0f;
}
References duration, E_NONE, BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), and BaseAction::SetTargetType().
AbilityAction() [2/3]
AbilityAction::AbilityAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const float duration_, ABILITYTYPE type_)
Definition at line 14 of file AbilityAction.cpp.
{
    SetName(name_);
    SetDiscription(discription_);
    SetActionType(action_);
    SetTargetType(target_);
    SetInteractionType(interaction_);
    SetActionID(actionID_);
    duration = duration_;
}
References duration, BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), and BaseAction::SetTargetType().
AbilityAction() [3/3]
AbilityAction::AbilityAction (AbilityAction *const other_)
Definition at line 25 of file AbilityAction.cpp.
{
    SetName(other_->ReturnName());
    SetDiscription(other_->ReturnDiscription());
    SetActionType(other_->ReturnActionType());
    SetInteractionType(other_->ReturnInteractionType());
    SetActionID(other_->ReturnActionID());
    duration = other_->ReturnDuration();
}
References duration, BaseAction::ReturnActionID(), BaseAction::ReturnActionType(), BaseAction::ReturnDiscription(), ReturnDuration(), BaseAction::ReturnInteractionType(), BaseAction::ReturnName(), BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), and BaseAction::SetName().
~AbilityAction()
AbilityAction::~AbilityAction ()
Definition at line 63 of file AbilityAction.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
CalculateAbilityValue()
float AbilityAction::CalculateAbilityValue () [private]
Definition at line 35 of file AbilityAction.cpp.
{
    //TO DO: implement an equation class.
}
OnDestroy()
void AbilityAction::OnDestroy ()
Definition at line 59 of file AbilityAction.cpp.
{
    //This will clear out any data.
}
ReturnAbilityType()
 ABILITYTYPE AbilityAction::ReturnAbilityType () const
Definition at line 55 of file AbilityAction.cpp.
{
    return abilityType;
}
References abilityType.
ReturnActionID()
uint32 BaseAction::ReturnActionID () const [inherited]
Return Action ID.
Definition at line 75 of file BaseAction.cpp.
{
    return actionID;
}
References BaseAction::actionID.
ReturnActionType()
 ACTIONTYPE BaseAction::ReturnActionType () const [inherited]
Return action type.
Definition at line 63 of file BaseAction.cpp.
{
    return action;
}
References BaseAction::action.
ReturnDiscription()
FString BaseAction::ReturnDiscription () const [inherited]
Return discription.
Definition at line 59 of file BaseAction.cpp.
{
    return discription;
}
References BaseAction::discription.
ReturnDuration()
float AbilityAction::ReturnDuration () const
Definition at line 43 of file AbilityAction.cpp.
{
    return duration;
}
References duration.
ReturnInteractionType()
 INTERACTIONTYPE BaseAction::ReturnInteractionType () const [inherited]
Return Interaction type.
Definition at line 71 of file BaseAction.cpp.
{
    return interaction;
}
References BaseAction::interaction.
ReturnModStatMap()
TMap< FString, float > AbilityAction::ReturnModStatMap ()
Definition at line 47 of file AbilityAction.cpp.
{
    return modStatMap;
}
References modStatMap.
ReturnName()
FString BaseAction::ReturnName () const [inherited]
Return Name.
ReturnTargetType()
 TARGETTYPE BaseAction::ReturnTargetType () const [inherited]
Return target type.
Definition at line 67 of file BaseAction.cpp.
{
    return target;
}
References BaseAction::target.
SetAbilityType()
void AbilityAction::SetAbilityType (const ABILITYTYPE type_)
Definition at line 51 of file AbilityAction.cpp.
{
    abilityType = type_;
}
References abilityType.
SetActionID()
void BaseAction::SetActionID (const uint32 actionID_) [inherited]
Sets action ID.
Definition at line 51 of file BaseAction.cpp.
{
    actionID = actionID_;
}
References BaseAction::actionID.
SetActionType()
void BaseAction::SetActionType (const ACTIONTYPE type_) [inherited]
Sets Actiontype.
Definition at line 39 of file BaseAction.cpp.
{
    action = type_;
}
References BaseAction::action.
SetDiscription()
void BaseAction::SetDiscription (const FString discription_) [inherited]
Sets Discription.
Definition at line 35 of file BaseAction.cpp.
{
    discription = discription_;
}
References BaseAction::discription.
SetDuration()
void AbilityAction::SetDuration (const float duration_)
Definition at line 39 of file AbilityAction.cpp.
{
    duration = duration_;
}
References duration.
SetInteractionType()
void BaseAction::SetInteractionType (const INTERACTIONTYPE type_) [inherited]
Sets interaction type.
Definition at line 47 of file BaseAction.cpp.
{
    interaction = type_;
}
References BaseAction::interaction.
SetName()
void BaseAction::SetName (const FString name_) [inherited]
Sets Name.
Definition at line 31 of file BaseAction.cpp.
{
    name = name_;
}
References BaseAction::name.
SetTargetType()
void BaseAction::SetTargetType (const TARGETTYPE type_) [inherited]
Sets target type.
Definition at line 43 of file BaseAction.cpp.
{
    target = type_;
}
References BaseAction::target.
Field Documentation
abilityType
 ABILITYTYPE AbilityAction::abilityType [private]
Definition at line 15 of file AbilityAction.h.
abilityValue
float AbilityAction::abilityValue [private]
Definition at line 14 of file AbilityAction.h.
action
 ACTIONTYPE BaseAction::action [private], [inherited]
Definition at line 67 of file BaseAction.h.
actionID
uint32 BaseAction::actionID [private], [inherited]
Definition at line 70 of file BaseAction.h.
discription
FString BaseAction::discription [private], [inherited]
Definition at line 66 of file BaseAction.h.
duration
float AbilityAction::duration [private]
Definition at line 13 of file AbilityAction.h.
interaction
 INTERACTIONTYPE BaseAction::interaction [private], [inherited]
Definition at line 69 of file BaseAction.h.
modStatMap
TMap<FString, float> AbilityAction::modStatMap [private]
Definition at line 16 of file AbilityAction.h.
name
FString BaseAction::name [private], [inherited]
Definition at line 65 of file BaseAction.h.
target
 TARGETTYPE BaseAction::target [private], [inherited]
Definition at line 68 of file BaseAction.h.
The documentation for this class was generated from the following files:
Battle_Box/Private/ActionClasses/ AbilityAction.h
Battle_Box/Private/ActionClasses/ AbilityAction.cpp