ItemAction Class Reference
#include <ItemAction.h>
Public Member Functions
void AddEffect (AbilityAction *const ability_)
Adds an effect to the items effects array.
uint32 GenerateID ()
 ItemAction ()
 ItemAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const uint32 value_, const DAMAGETYPE damageType_, const TArray< AbilityAction * > effectArray_)
 ItemAction (const ItemAction *other_)
void OnDestroy ()
uint32 ReturnActionID () const
Return Action ID.
 ACTIONTYPE ReturnActionType () const
Return action type.
 DAMAGETYPE ReturnDamageType () const
Returns Damage type.
FString ReturnDiscription () const
Return discription.
TArray< AbilityAction * > ReturnEffectList () const
Returns Effect array.
 INTERACTIONTYPE ReturnInteractionType () const
Return Interaction type.
 ITEMTYPE ReturnItemType () const
Returns itemType.
FString ReturnName () const
Return Name.
 STATACTION ReturnStatActionType () const
Returns the stat action type.
TMap< FString, float > ReturnStatMap () const
Return statModMap.
 TARGETTYPE ReturnTargetType () const
Return target type.
uint32 ReturnValue () const
Returnsitem value.
void SetActionID (const uint32 actionID_)
Sets action ID.
void SetActionType (const ACTIONTYPE type_)
Sets Actiontype.
void SetDamageType (const DAMAGETYPE type_)
Set Damage type.
void SetDiscription (const FString discription_)
Sets Discription.
void SetInteractionType (const INTERACTIONTYPE type_)
Sets interaction type.
void SetName (const FString name_)
Sets Name.
void SetStatActionType (const STATACTION type_)
Set Stat Action type.
void SetTargetType (const TARGETTYPE type_)
Sets target type.
void SetType (const ITEMTYPE type_)
Set Item type.
void SetValue (const uint32 value_)
Set item Value.
 ~ItemAction ()
Private Attributes
 ACTIONTYPE action
uint32 actionID
 DAMAGETYPE damageType
FString discription
TArray< AbilityAction * > effectList
 INTERACTIONTYPE interaction
FString name
 STATACTION statAction
TMap< FString, float > statModMap
 TARGETTYPE target
 ITEMTYPE type
uint32 value
Detailed Description
Definition at line 21 of file ItemAction.h.
Constructor & Destructor Documentation
ItemAction() [1/3]
ItemAction::ItemAction ()
Definition at line 4 of file ItemAction.cpp.
                       : effectList(TArray<AbilityAction*>())
{
    SetName("");
    SetDiscription("");
    SetActionType(ACTIONTYPE::E_NONE);
    SetTargetType(TARGETTYPE::E_NONE);
    SetInteractionType(INTERACTIONTYPE::E_NONE);
    SetActionID(00);
    SetValue(00);
    SetDamageType(DAMAGETYPE::E_NONE);
}
References E_NONE, BaseAction::SetActionID(), BaseAction::SetActionType(), SetDamageType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), BaseAction::SetTargetType(), and SetValue().
ItemAction() [2/3]
ItemAction::ItemAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const uint32 value_, const DAMAGETYPE damageType_, const TArray< AbilityAction * > effectArray_)
Definition at line 15 of file ItemAction.cpp.
{
    SetName(name_);
    SetDiscription(discription_);
    SetActionType(action_);
    SetTargetType(target_);
    SetInteractionType(interaction_);
    SetActionID(actionID_);
    
    value = value_;
    effectList = effectArray_;
}
References effectList, BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), BaseAction::SetTargetType(), and value.
ItemAction() [3/3]
ItemAction::ItemAction (const ItemAction * other_)
Definition at line 28 of file ItemAction.cpp.
{
    SetName(other_->ReturnName());
    SetDiscription(other_->ReturnDiscription());
    SetActionType(other_ ->ReturnActionType());
    SetTargetType(other_->ReturnTargetType());
    SetInteractionType(other_->ReturnInteractionType());
    SetActionID(other_->ReturnActionID());
    SetValue(other_->ReturnValue());
}
References BaseAction::ReturnActionID(), BaseAction::ReturnActionType(), BaseAction::ReturnDiscription(), BaseAction::ReturnInteractionType(), BaseAction::ReturnName(), BaseAction::ReturnTargetType(), ReturnValue(), BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), BaseAction::SetTargetType(), and SetValue().
~ItemAction()
ItemAction::~ItemAction ()
Definition at line 78 of file ItemAction.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
AddEffect()
void ItemAction::AddEffect (AbilityAction *const ability_)
Adds an effect to the items effects array.
Definition at line 50 of file ItemAction.cpp.
{
    effectList.Add(ability_);
}
References effectList.
GenerateID()
uint32 BaseAction::GenerateID () [inherited]
Definition at line 39 of file BaseAction.cpp.
{
    //Generate a uniqe ID for the action when made.
    return (uint32)FMath::FRandRange(0.0f, 100000.0f);
}
OnDestroy()
void ItemAction::OnDestroy ()
Definition at line 74 of file ItemAction.cpp.
{
    //Clean up method
}
ReturnActionID()
uint32 BaseAction::ReturnActionID () const [inherited]
Return Action ID.
Definition at line 96 of file BaseAction.cpp.
{
    return actionID;
}
References BaseAction::actionID.
ReturnActionType()
 ACTIONTYPE BaseAction::ReturnActionType () const [inherited]
Return action type.
Definition at line 80 of file BaseAction.cpp.
{
    return action;
}
References BaseAction::action.
ReturnDamageType()
 DAMAGETYPE ItemAction::ReturnDamageType () const
Returns Damage type.
Definition at line 62 of file ItemAction.cpp.
{
    return damageType;
}
References damageType.
ReturnDiscription()
FString BaseAction::ReturnDiscription () const [inherited]
Return discription.
Definition at line 76 of file BaseAction.cpp.
{
    return discription;
}
References BaseAction::discription.
ReturnEffectList()
TArray< AbilityAction * > ItemAction::ReturnEffectList () const
Returns Effect array.
Definition at line 70 of file ItemAction.cpp.
{
    return effectList;
}
References effectList.
ReturnInteractionType()
 INTERACTIONTYPE BaseAction::ReturnInteractionType () const [inherited]
Return Interaction type.
Definition at line 88 of file BaseAction.cpp.
{
    return interaction;
}
References BaseAction::interaction.
ReturnItemType()
 ITEMTYPE ItemAction::ReturnItemType () const
Returns itemType.
Definition at line 54 of file ItemAction.cpp.
{
    return type;
}
References type.
ReturnName()
FString BaseAction::ReturnName () const [inherited]
Return Name.
ReturnStatActionType()
 STATACTION BaseAction::ReturnStatActionType () const [inherited]
Returns the stat action type.
Definition at line 92 of file BaseAction.cpp.
{
    return statAction;
}
References BaseAction::statAction.
ReturnStatMap()
TMap< FString, float > ItemAction::ReturnStatMap () const
Return statModMap.
Definition at line 66 of file ItemAction.cpp.
{
    return statModMap;
}
References statModMap.
ReturnTargetType()
 TARGETTYPE BaseAction::ReturnTargetType () const [inherited]
Return target type.
Definition at line 84 of file BaseAction.cpp.
{
    return target;
}
References BaseAction::target.
ReturnValue()
uint32 ItemAction::ReturnValue () const
Returnsitem value.
Definition at line 58 of file ItemAction.cpp.
{
    return value;
}
References value.
SetActionID()
void BaseAction::SetActionID (const uint32 actionID_) [inherited]
Sets action ID.
Definition at line 68 of file BaseAction.cpp.
{
    actionID = actionID_;
}
References BaseAction::actionID.
SetActionType()
void BaseAction::SetActionType (const ACTIONTYPE type_) [inherited]
Sets Actiontype.
Definition at line 52 of file BaseAction.cpp.
{
    action = type_;
}
References BaseAction::action.
SetDamageType()
void ItemAction::SetDamageType (const DAMAGETYPE type_)
Set Damage type.
Definition at line 42 of file ItemAction.cpp.
{
    damageType = type_;
}
References damageType.
SetDiscription()
void BaseAction::SetDiscription (const FString discription_) [inherited]
Sets Discription.
Definition at line 48 of file BaseAction.cpp.
{
    discription = discription_;
}
References BaseAction::discription.
SetInteractionType()
void BaseAction::SetInteractionType (const INTERACTIONTYPE type_) [inherited]
Sets interaction type.
Definition at line 60 of file BaseAction.cpp.
{
    interaction = type_;
}
References BaseAction::interaction.
SetName()
void BaseAction::SetName (const FString name_) [inherited]
Sets Name.
Definition at line 44 of file BaseAction.cpp.
{
    name = name_;
}
References BaseAction::name.
SetStatActionType()
void BaseAction::SetStatActionType (const STATACTION type_) [inherited]
Set Stat Action type.
Definition at line 64 of file BaseAction.cpp.
{
    statAction = type_;
}
References BaseAction::statAction.
SetTargetType()
void BaseAction::SetTargetType (const TARGETTYPE type_) [inherited]
Sets target type.
Definition at line 56 of file BaseAction.cpp.
{
    target = type_;
}
References BaseAction::target.
SetType()
void ItemAction::SetType (const ITEMTYPE type_)
Set Item type.
Definition at line 46 of file ItemAction.cpp.
{
    type = type_;
}
References type.
SetValue()
void ItemAction::SetValue (const uint32 value_)
Set item Value.
Definition at line 38 of file ItemAction.cpp.
{
    value = value_;
}
References value.
Field Documentation
action
 ACTIONTYPE BaseAction::action [private], [inherited]
Definition at line 70 of file BaseAction.h.
actionID
uint32 BaseAction::actionID [private], [inherited]
Definition at line 74 of file BaseAction.h.
damageType
 DAMAGETYPE ItemAction::damageType [private]
Definition at line 28 of file ItemAction.h.
discription
FString BaseAction::discription [private], [inherited]
Definition at line 69 of file BaseAction.h.
effectList
TArray< AbilityAction*> ItemAction::effectList [private]
Definition at line 26 of file ItemAction.h.
interaction
 INTERACTIONTYPE BaseAction::interaction [private], [inherited]
Definition at line 73 of file BaseAction.h.
name
FString BaseAction::name [private], [inherited]
Definition at line 68 of file BaseAction.h.
statAction
 STATACTION BaseAction::statAction [private], [inherited]
Definition at line 72 of file BaseAction.h.
statModMap
TMap<FString, float> ItemAction::statModMap [private]
Definition at line 27 of file ItemAction.h.
target
 TARGETTYPE BaseAction::target [private], [inherited]
Definition at line 71 of file BaseAction.h.
type
 ITEMTYPE ItemAction::type [private]
Definition at line 24 of file ItemAction.h.
value
uint32 ItemAction::value [private]
Definition at line 25 of file ItemAction.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ActionClasses/ ItemAction.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ActionClasses/ ItemAction.cpp