JsonReceiver Class Reference
#include <JsonReceiver.h>
Public Member Functions
void InitiateClass ()
 JsonReceiver ()
void ReadActionObject (const FString &fileName_)
void ReadEquationObject (const FString &fileName_)
void ReadStatSheetObject (const FString fileName_)
bool ResetJsonObject ()
void WriteActionObject (BaseAction *const action_)
void WriteEquationObject ()
void WriteStatSheetObject (StatSheetObject *const sheet_)
 ~JsonReceiver ()
Private Member Functions
TArray< TSharedPtr< FJsonValue > > MakeIDJsonArray (StatSheetObject *const sheet_, const FString Name_)
Private Attributes
FString Directory
TSharedPtr< FJsonObject > JsonObject
TSharedPtr< TJsonReader<> > JsonReader
TSharedPtr< TJsonWriter<> > JsonWriter
FString readFileString
FString writeFileString
Detailed Description
Definition at line 17 of file JsonReceiver.h.
Constructor & Destructor Documentation
JsonReceiver()
JsonReceiver::JsonReceiver ()
Definition at line 118 of file JsonReceiver.cpp.
{
}
~JsonReceiver()
JsonReceiver::~JsonReceiver ()
Definition at line 364 of file JsonReceiver.cpp.
{
}
Member Function Documentation
InitiateClass()
void JsonReceiver::InitiateClass ()
Definition at line 121 of file JsonReceiver.cpp.
{
    JsonObject = MakeShareable(new FJsonObject);
    Directory = FPaths::ProjectPluginsDir() + "/Battle_Box/FileResource";
    JsonWriter = TJsonWriterFactory<>::Create(&writeFileString);
    BattleBoxFileManager::VerifyOnCreateDirectory(Directory);
}
References Directory, JsonObject, JsonWriter, BattleBoxFileManager::VerifyOnCreateDirectory(), and writeFileString.
MakeIDJsonArray()
TArray< TSharedPtr< FJsonValue > > JsonReceiver::MakeIDJsonArray (StatSheetObject *const sheet_, const FString Name_) [private]
Definition at line 317 of file JsonReceiver.cpp.
{
    TArray<TSharedPtr<FJsonValue>> Array;
    
    if (Name_ == "commands")
    {
        for (auto& i : sheet_->ReturnCommandMap())
        {
            TSharedPtr<FJsonValue> value = MakeShareable(new FJsonValueNumber(static_cast<double>(i.Value->ReturnActionID())));
            Array.Add(value);
        }
    }
    if (Name_ == "items")
    {
        for (auto& i : sheet_->ReturnItemMap())
        {
            TSharedPtr<FJsonValue> value = MakeShareable(new FJsonValueNumber(static_cast<double>(i.Value->ReturnActionID())));
            Array.Add(value);
        }
    }
    if (Name_ == "abilities")
    {
        for (auto& i : sheet_->ReturnAbilityMap())
        {
            TSharedPtr<FJsonValue> value = MakeShareable(new FJsonValueNumber(static_cast<double>(i.Value->ReturnActionID())));
            Array.Add(value);
        }
    }
    if (Name_ == "equipmint")
    {
        for (auto& i : sheet_->ReturnEquipmentMap())
        {
            TSharedPtr<FJsonValue> value = MakeShareable(new FJsonValueNumber(static_cast<double>(i.Value->ReturnActionID())));
            Array.Add(value);
        }
    }
    return Array;
}
References StatSheetObject::ReturnAbilityMap(), StatSheetObject::ReturnCommandMap(), StatSheetObject::ReturnEquipmentMap(), and StatSheetObject::ReturnItemMap().
ReadActionObject()
void JsonReceiver::ReadActionObject (const FString & fileName_)
Definition at line 140 of file JsonReceiver.cpp.
{
    //This will read from a json file for action object
    //TODO::
    readFileString = BattleBoxFileManager::ReadFile(Directory + "/ActionSheets", fileName_);
    JsonReader = TJsonReaderFactory<>::Create(readFileString);
    if (FJsonSerializer::Deserialize(JsonReader.ToSharedRef(), JsonObject))
    {
        //RTTI to find what the dirived action is
        ACTIONTYPE action = static_cast<ACTIONTYPE>((int)JsonObject.Get()->GetNumberField("ActionType"));
        if (action == ACTIONTYPE::E_COMMAND)
        {
            commandData data;
            data.name = JsonObject.Get()->GetStringField("Name");
            data.discription = JsonObject.Get()->GetStringField("Discription");
            data.actionID = static_cast<uint32>((int)JsonObject.Get()->GetNumberField("ActionID"));
            data.actionType = static_cast<ACTIONTYPE>((int)JsonObject.Get()->GetNumberField("ActionType"));
            data.targetType = static_cast<TARGETTYPE>((int)JsonObject.Get()->GetNumberField("TargetType"));
            
            double tmp;
            if (JsonObject.Get()->TryGetNumberField("StatAction", tmp))
                data.statAction = static_cast<STATACTION>((int)JsonObject.Get()->GetNumberField("StatAction"));
            else
                data.statAction = STATACTION::E_NONE;
            data.currentWeapon = static_cast<WEAPONTYPE>((int)JsonObject.Get()->GetNumberField("CurrentWeapon"));
            data.commandActionID = static_cast<uint32>(JsonObject.Get()->GetNumberField("BaseActionID"));
        }
        if (action == ACTIONTYPE::E_ITEM)
        {
            ItemData data;
            data.name = JsonObject.Get()->GetStringField("Name");
            data.discription = JsonObject.Get()->GetStringField("Discription");
            data.actionID = static_cast<uint32>((int)JsonObject.Get()->GetNumberField("ActionID"));
            data.actionType = static_cast<ACTIONTYPE>((int)JsonObject.Get()->GetNumberField("ActionType"));
            data.targetType = static_cast<TARGETTYPE>((int)JsonObject.Get()->GetNumberField("TargetType"));
            double tmp;
            if (JsonObject.Get()->TryGetNumberField("StatAction", tmp))
                data.statAction = static_cast<STATACTION>((int)JsonObject.Get()->GetNumberField("StatAction"));
            else
                data.statAction = STATACTION::E_NONE;
            data.itemType = static_cast<ITEMTYPE>((int)JsonObject.Get()->GetIntegerField("ItemAction"));
            data.value = JsonObject.Get()->GetIntegerField("Value");
            data.effectIDList = TArray<uint32>(JsonObject.Get()->GetArrayField("EffectListID"));
        }
        if (action == ACTIONTYPE::E_ABILITY)
        {
            AbilityData data;
            data.name = JsonObject.Get()->GetStringField("Name");
            data.discription = JsonObject.Get()->GetStringField("Discription");
            data.actionID = static_cast<uint32>((int)JsonObject.Get()->GetNumberField("ActionID"));
            data.actionType = static_cast<ACTIONTYPE>((int)JsonObject.Get()->GetNumberField("ActionType"));
            data.targetType = static_cast<TARGETTYPE>((int)JsonObject.Get()->GetNumberField("TargetType"));
            double tmp;
            if (JsonObject.Get()->TryGetNumberField("StatAction", tmp))
                data.statAction = static_cast<STATACTION>((int)JsonObject.Get()->GetNumberField("StatAction"));
            else
                data.statAction = STATACTION::E_NONE;
            data.abilityType = static_cast<ABILITYTYPE>((int)JsonObject.Get()->GetNumberField("AbilityType"));
            data.duration = static_cast<float>(JsonObject.Get()->GetNumberField("Duration"));
            data.abilityValue = static_cast<float>(JsonObject.Get()->GetNumberField("AbilityValue"));
        }
    }
}
References AbilityData::abilityType, AbilityData::abilityValue, commandData::actionID, ItemData::actionID, AbilityData::actionID, commandData::actionType, ItemData::actionType, AbilityData::actionType, commandData::commandActionID, commandData::currentWeapon, Directory, commandData::discription, ItemData::discription, AbilityData::discription, AbilityData::duration, E_ABILITY, E_COMMAND, E_ITEM, E_NONE, ItemData::effectIDList, ItemData::itemType, JsonObject, JsonReader, commandData::name, ItemData::name, AbilityData::name, BattleBoxFileManager::ReadFile(), readFileString, commandData::statAction, ItemData::statAction, AbilityData::statAction, commandData::targetType, ItemData::targetType, AbilityData::targetType, and ItemData::value.
ReadEquationObject()
void JsonReceiver::ReadEquationObject (const FString & fileName_)
Definition at line 207 of file JsonReceiver.cpp.
{
    //This will read from a json file for equation object
    //TODO::
}
ReadStatSheetObject()
void JsonReceiver::ReadStatSheetObject (const FString fileName_)
Definition at line 128 of file JsonReceiver.cpp.
{
    //This will read from a json file for statsheetobject
    //TODO::
    readFileString = BattleBoxFileManager::ReadFile(Directory + "/StatSheets", fileName_);
    JsonReader = TJsonReaderFactory<>::Create(readFileString);
    if (FJsonSerializer::Deserialize(JsonReader.ToSharedRef(), JsonObject))
    {
        JsonObject.Get()->GetStringField("Name");
        JsonObject.Get()->GetStringField("Tag");
    }
}
References Directory, JsonObject, JsonReader, BattleBoxFileManager::ReadFile(), and readFileString.
ResetJsonObject()
bool JsonReceiver::ResetJsonObject ()
Definition at line 355 of file JsonReceiver.cpp.
{
    if (JsonObject.Get())
    {
        JsonObject.Reset();
        return true;
    }
    return false;
}
References JsonObject.
WriteActionObject()
void JsonReceiver::WriteActionObject (BaseAction *const action_)
Definition at line 237 of file JsonReceiver.cpp.
{
    //This will write to a json file for a action object
    //TODO:: Write the object, serialize, save it to a file.
    
    if (action_->ReturnActionType() == ACTIONTYPE::E_COMMAND)
    {
        CommandAction* command = dynamic_cast<CommandAction*>(action_);
        JsonObject.Get()->SetStringField("Name", command->ReturnName());
        JsonObject.Get()->SetStringField("Discription", command->ReturnDiscription());
        JsonObject.Get()->SetNumberField("ActionID", static_cast<double>(command->ReturnActionID()));
        JsonObject.Get()->SetNumberField("ActionType", static_cast<double>(command->ReturnActionID()));
        JsonObject.Get()->SetNumberField("TargetType", static_cast<double>(command->ReturnTargetType()));
        JsonObject.Get()->SetNumberField("StatAction", static_cast<double>(command->ReturnStatActionType()));
        JsonObject.Get()->SetNumberField("InteractionType", static_cast<double>(command->ReturnInteractionType()));
        JsonObject.Get()->SetNumberField("CurrentWeapon", static_cast<double>(command->ReturnWeaponType()));
        JsonObject.Get()->SetNumberField("BaseActionID", static_cast<double>(command->ReturnAction()->ReturnActionID()));
        JsonWriter = TJsonWriterFactory<>::Create(&writeFileString);
        BattleBoxFileManager::WriteTextFile(Directory, writeFileString, action_->ReturnName() + ".json", false);
    }
    if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
    {
        ItemAction* Item = dynamic_cast<ItemAction*>(action_);
        JsonObject.Get()->SetStringField("Name", Item->ReturnName());
        JsonObject.Get()->SetStringField("Discription", Item->ReturnDiscription());
        JsonObject.Get()->SetNumberField("ActionID", static_cast<double>(Item->ReturnActionID()));
        JsonObject.Get()->SetNumberField("ActionType", static_cast<double>(Item->ReturnActionID()));
        JsonObject.Get()->SetNumberField("TargetType", static_cast<double>(Item->ReturnTargetType()));
        JsonObject.Get()->SetNumberField("StatAction", static_cast<double>(Item->ReturnStatActionType()));
        JsonObject.Get()->SetNumberField("InteractionType", static_cast<double>(Item->ReturnInteractionType()));
        JsonObject.Get()->SetNumberField("ItemType", static_cast<double>(Item->ReturnItemType()));
        JsonObject.Get()->SetNumberField("Value", static_cast<double>(Item->ReturnValue()));
        JsonObject.Get()->SetNumberField("DamageType", static_cast<double>(Item->ReturnDamageType()));
        TArray<TSharedPtr<FJsonValue>> Array;
        TSharedPtr<FJsonObject> statObject;
        
        for (auto& i : Item->ReturnEffectList())
        {
            TSharedPtr<FJsonValue> value = MakeShareable(new FJsonValueNumber(i->ReturnActionID()));
            Array.Add(value);
        }
        JsonObject.Get()->SetArrayField("EffectListID", Array);
        for (auto& i : Item->ReturnStatMap())
        {
            statObject.Get()->SetNumberField(i.Key, i.Value);
        }
        JsonWriter = TJsonWriterFactory<>::Create(&writeFileString);
        BattleBoxFileManager::WriteTextFile(Directory, writeFileString, action_->ReturnName() + ".json", false);
    }
    if(action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
    {
        AbilityAction* Ability = dynamic_cast<AbilityAction*>(action_);
        JsonObject.Get()->SetStringField("Name", Ability->ReturnName());
        JsonObject.Get()->SetStringField("Discription", Ability->ReturnDiscription());
        JsonObject.Get()->SetNumberField("ActionID", static_cast<double>(Ability->ReturnActionID()));
        JsonObject.Get()->SetNumberField("ActionType", static_cast<double>(Ability->ReturnActionID()));
        JsonObject.Get()->SetNumberField("TargetType", static_cast<double>(Ability->ReturnTargetType()));
        JsonObject.Get()->SetNumberField("StatAction", static_cast<double>(Ability->ReturnStatActionType()));
        JsonObject.Get()->SetNumberField("InteractionType", static_cast<double>(Ability->ReturnInteractionType()));
        JsonObject.Get()->SetNumberField("Duration", static_cast<double>(Ability->ReturnDuration()));
        JsonObject.Get()->SetNumberField("AbilityValue", static_cast<double>(Ability->ReturnAbilityValue()));
        JsonObject.Get()->SetNumberField("AbilityType", static_cast<double>(Ability->ReturnAbilityType()));
        TArray<TSharedPtr<FJsonValue>> Array;
        
    JsonWriter = TJsonWriterFactory<>::Create(&writeFileString);
    BattleBoxFileManager::WriteTextFile(Directory, writeFileString, action_->ReturnName() + ".json", false);
    }
    ResetJsonObject();
}
References Directory, E_ABILITY, E_COMMAND, E_ITEM, JsonObject, JsonWriter, ResetJsonObject(), AbilityAction::ReturnAbilityType(), AbilityAction::ReturnAbilityValue(), CommandAction::ReturnAction(), BaseAction::ReturnActionID(), BaseAction::ReturnActionType(), ItemAction::ReturnDamageType(), BaseAction::ReturnDiscription(), AbilityAction::ReturnDuration(), ItemAction::ReturnEffectList(), BaseAction::ReturnInteractionType(), ItemAction::ReturnItemType(), BaseAction::ReturnName(), BaseAction::ReturnStatActionType(), ItemAction::ReturnStatMap(), BaseAction::ReturnTargetType(), ItemAction::ReturnValue(), CommandAction::ReturnWeaponType(), writeFileString, and BattleBoxFileManager::WriteTextFile().
WriteEquationObject()
void JsonReceiver::WriteEquationObject ()
Definition at line 312 of file JsonReceiver.cpp.
{
    //This will write to a json file for a equation object.
    //TODO:: Write the object, serialize, save it to a file.
}
WriteStatSheetObject()
void JsonReceiver::WriteStatSheetObject (StatSheetObject *const sheet_)
Definition at line 212 of file JsonReceiver.cpp.
{
    //This will write to a json file for a statsheetobject
    //TODO:: Write the object, serialize, save it to a file
    JsonObject.Get()->SetStringField("Name", sheet_->ReturnName());
    JsonObject.Get()->SetStringField("Tag", sheet_->ReturnTag());
    JsonObject.Get()->SetArrayField("Commands", MakeIDJsonArray(sheet_, "commands"));
    JsonObject.Get()->SetArrayField("Items", MakeIDJsonArray(sheet_, "items"));
    JsonObject.Get()->SetArrayField("abilities", MakeIDJsonArray(sheet_, "abilites"));
    JsonObject.Get()->SetArrayField("equipment", MakeIDJsonArray(sheet_, "equipment"));
    TSharedPtr<FJsonObject> StatObject;
    //This does not work when you re-enginer.
    for (auto& i : sheet_->ReturnStatMap())
    {
        StatObject.Get()->SetNumberField(i.Key, (double)i.Value);
    }
    JsonObject.Get()->SetObjectField("StatObject", StatObject);
    
    FJsonSerializer::Serialize(JsonObject.ToSharedRef(), JsonWriter.ToSharedRef());
    BattleBoxFileManager::WriteTextFile(Directory, writeFileString, sheet_->ReturnName() + ".json", false);
    ResetJsonObject();
}
References Directory, JsonObject, JsonWriter, MakeIDJsonArray(), ResetJsonObject(), StatSheetObject::ReturnName(), StatSheetObject::ReturnStatMap(), StatSheetObject::ReturnTag(), writeFileString, and BattleBoxFileManager::WriteTextFile().
Field Documentation
Directory
FString JsonReceiver::Directory [private]
Definition at line 23 of file JsonReceiver.h.
JsonObject
TSharedPtr<FJsonObject> JsonReceiver::JsonObject [private]
Definition at line 20 of file JsonReceiver.h.
JsonReader
TSharedPtr<TJsonReader<> > JsonReceiver::JsonReader [private]
Definition at line 22 of file JsonReceiver.h.
JsonWriter
TSharedPtr<TJsonWriter<> > JsonReceiver::JsonWriter [private]
Definition at line 21 of file JsonReceiver.h.
readFileString
FString JsonReceiver::readFileString [private]
Definition at line 24 of file JsonReceiver.h.
writeFileString
FString JsonReceiver::writeFileString [private]
Definition at line 25 of file JsonReceiver.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ JsonReceiver.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ JsonReceiver.cpp