StatSystem Class Reference
#include <StatSystem.h>
Public Member Functions
 StatSystem & operator= (const StatSystem &)=delete
 StatSystem & operator= (StatSystem &&)=delete
 StatSystem ()=delete
 StatSystem (const StatSystem &)=delete
 StatSystem (StatSystem &&)=delete
 ~StatSystem ()
Static Public Member Functions
static void Addtarget (StatSheetObject *const target_)
Adds another target to the target array.
static void CalculateStat (const bool IsSingleTarget_, BaseAction *const action_)
static void ModifiyStat (StatSheetObject *const target_, const float value, const FString name_)
This updates the stats based on the name.
static void OnDestroy ()
static void SetTarget (StatSheetObject *const target_)
Sets target.
Static Private Member Functions
static void AddStatModifier (StatSheetObject *const target_, BaseAction *const action_)
Adds the specific modification by the baseaction.
static void AddTmpModifier (StatSheetObject *const target_, BaseAction *const action_, const float duration_)
Adds a modificationtemporarly.
static void BaseCalculate (const bool IsSingleTarget_, BaseAction *const action_)
Base calculation for any dirieved system classes.
static void RemoveModifier (StatSheetObject *const target_, BaseAction *const action_)
Removes the specific modification by the baseaction.
static void RemoveTmpModifier (StatSheetObject *const target_, BaseAction *action_, const float duration_)
Removes a modification temporarly.
Static Private Attributes
static StatSheetObject * target = nullptr
static TArray< StatSheetObject * > targets = TArray< StatSheetObject*>()
Detailed Description
Definition at line 9 of file StatSystem.h.
Constructor & Destructor Documentation
StatSystem() [1/3]
StatSystem::StatSystem (const StatSystem &) [delete]
StatSystem() [2/3]
StatSystem::StatSystem (StatSystem &&) [delete]
StatSystem() [3/3]
StatSystem::StatSystem () [delete]
~StatSystem()
StatSystem::~StatSystem ()
Definition at line 296 of file StatSystem.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
AddStatModifier()
void StatSystem::AddStatModifier (StatSheetObject *const target_, BaseAction *const action_) [static], [private]
Adds the specific modification by the baseaction.
Definition at line 190 of file StatSystem.cpp.
{
    if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
    {
        ItemAction* item = dynamic_cast<ItemAction*>(action_);
        if (item->ReturnItemType() == ITEMTYPE::E_CONSUMABLE)
        {
            for (auto& effect : item->ReturnEffectList())
            {
                if (effect->ReturnAbilityType() == ABILITYTYPE::E_MODIFIYER)
                {
                    for (auto& statMod : effect->ReturnModStatMap())
                    {
                        ModifiyStat(target_, statMod.Value, statMod.Key);
                    }
                }
                else if (effect->ReturnAbilityType() == ABILITYTYPE::E_TMP_MODIFIYER)
                {
                    //This will go throught the modifyer process
                    //TO DO: Finish the proccess code for the tmp modifiyer.
                }
                else if (effect->ReturnAbilityType() == ABILITYTYPE::E_DAMAGE_MODIFYER)
                {
                    //TO DO: turn systems to static classes.
                }
            }
        }
        else if (item->ReturnItemType() == ITEMTYPE::E_ARMOR || item->ReturnItemType() == ITEMTYPE::E_WEAPON)
        {
            for (auto& effect : item->ReturnEffectList())
            {
                for(auto& statMod : effect->ReturnModStatMap())
                {
                    ModifiyStat(target_, statMod.Value, statMod.Key);
                }
            }
        }
    }
    else if (action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
    {
        AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
        for(auto& statMod : ability->ReturnModStatMap())
        {
            ModifiyStat(target_, statMod.Value, statMod.Key);
        }
    }
    else
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error(action_->ReturnName() + " does not have an modification in this action.", "StatSystem.cpp", __LINE__);
        return;
    }
}
References E_ABILITY, E_ARMOR, E_CONSUMABLE, E_DAMAGE_MODIFYER, E_ERROR, E_ITEM, E_MODIFIYER, E_TMP_MODIFIYER, E_WEAPON, Debugger::Error(), ModifiyStat(), BaseAction::ReturnActionType(), ItemAction::ReturnEffectList(), ItemAction::ReturnItemType(), AbilityAction::ReturnModStatMap(), BaseAction::ReturnName(), and Debugger::SetSeverity().
Addtarget()
void StatSystem::Addtarget (StatSheetObject *const target_) [static]
Adds another target to the target array.
Definition at line 288 of file StatSystem.cpp.
{
    targets.Add(target_);
}
References targets.
AddTmpModifier()
void StatSystem::AddTmpModifier (StatSheetObject *const target_, BaseAction *const action_, const float duration_) [static], [private]
Adds a modificationtemporarly.
Definition at line 272 of file StatSystem.cpp.
{
    //This will add a modifier then remove it in a timer.
}
BaseCalculate()
void StatSystem::BaseCalculate (const bool IsSingledTarget_, BaseAction *const action_) [static], [private], [virtual]
Base calculation for any dirieved system classes.
Implements BaseSystem .
Definition at line 17 of file StatSystem.cpp.
{
    if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
    {
        ItemAction* item = dynamic_cast<ItemAction*>(action_);
        if (IsSingledTarget_)
        {
            if (target == nullptr)
            {
                for (auto& ability : item->ReturnEffectList())
                {
                    if (ability->ReturnStatActionType() == STATACTION::E_ADD)
                    {
                        AddStatModifier(target, action_);
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_REMOVE)
                    {
                        RemoveModifier(target, ability);
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_TMP_ADD)
                    {
                        AddTmpModifier(target, ability, ability->ReturnDuration());
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_TMP_REMOVE)
                    {
                        RemoveTmpModifier(target, ability, ability->ReturnDuration());
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error(action_->ReturnName() + " Could not be modified", "StatSystem.cpp", __LINE__);
                        return;
                    }
                }
            }
            else
            {
                Debugger::SetSeverity(MessageType::E_ERROR);
                Debugger::Error("Target not avalable. Please set target if null", "StatSystem.cpp", __LINE__);
                return;
            }
        }
        else if (!IsSingledTarget_)
        {
            if (targets.Num > 0)
            {
                for (auto& i : targets)
                {
                    for (auto& ability : item->ReturnEffectList())
                    {
                        if (ability->ReturnStatActionType() == STATACTION::E_ADD)
                        {
                            AddStatModifier(i, action_);
                        }
                        else if (ability->ReturnStatActionType() == STATACTION::E_REMOVE)
                        {
                            RemoveModifier(i, ability);
                        }
                        else if (ability->ReturnStatActionType() == STATACTION::E_TMP_ADD)
                        {
                            AddTmpModifier(i, ability, ability->ReturnDuration());
                        }
                        else if (ability->ReturnStatActionType() == STATACTION::E_TMP_REMOVE)
                        {
                            RemoveTmpModifier(i, ability, ability->ReturnDuration());
                        }
                        else
                        {
                            Debugger::SetSeverity(MessageType::E_ERROR);
                            Debugger::Error(action_->ReturnName() + " Could not be modified", "StatSystem.cpp", __LINE__);
                            return;
                        }
                    }
                }
            }
            else
            {
                Debugger::SetSeverity(MessageType::E_ERROR);
                Debugger::Error("No targets avalable it the array. Please insert a target before calculating.", "StatSystem.cpp", __LINE__);
                return;
            }
        }
    }
    else if (action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
    {
        AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
        if (IsSingledTarget_)
        {
            if (target == nullptr)
            {
                if (ability->ReturnStatActionType() == STATACTION::E_ADD)
                {
                    AddStatModifier(target, action_);
                }
                else if (ability->ReturnStatActionType() == STATACTION::E_REMOVE)
                {
                    RemoveModifier(target, ability);
                }
                else if (ability->ReturnStatActionType() == STATACTION::E_TMP_ADD)
                {
                    AddTmpModifier(target, ability, ability->ReturnDuration());
                }
                else if (ability->ReturnStatActionType() == STATACTION::E_TMP_REMOVE)
                {
                    RemoveTmpModifier(target, ability, ability->ReturnDuration());
                }
                else
                {
                    Debugger::SetSeverity(MessageType::E_ERROR);
                    Debugger::Error(action_->ReturnName() + " Could not be modified", "StatSystem.cpp", __LINE__);
                    return;
                }
            }
            else
            {
                Debugger::SetSeverity(MessageType::E_ERROR);
                Debugger::Error("Target not avalable. Please set target if null", "StatSystem.cpp", __LINE__);
                return;
            }
        }
        else if(!IsSingledTarget_)
        {
            if (targets.Num > 0)
            {
                for (auto& i : targets)
                {
                    if (ability->ReturnStatActionType() == STATACTION::E_ADD)
                    {
                        AddStatModifier(i, action_);
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_REMOVE)
                    {
                        RemoveModifier(i, ability);
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_TMP_ADD)
                    {
                        AddTmpModifier(i, ability, ability->ReturnDuration());
                    }
                    else if (ability->ReturnStatActionType() == STATACTION::E_TMP_REMOVE)
                    {
                        RemoveTmpModifier(i, ability, ability->ReturnDuration());
                    }
                    else
                    {
                        Debugger::SetSeverity(MessageType::E_ERROR);
                        Debugger::Error(action_->ReturnName() + " Could not be modified", "StatSystem.cpp", __LINE__);
                        return;
                    }
                }
            }
            else
            {
                Debugger::SetSeverity(MessageType::E_ERROR);
                Debugger::Error("No targets avalable it the array. Please insert a target before calculating.", "StatSystem.cpp", __LINE__);
                return;
            }
        }
    }
}
References AddStatModifier(), AddTmpModifier(), E_ABILITY, E_ADD, E_ERROR, E_ITEM, E_REMOVE, E_TMP_ADD, E_TMP_REMOVE, Debugger::Error(), RemoveModifier(), RemoveTmpModifier(), BaseAction::ReturnActionType(), AbilityAction::ReturnDuration(), ItemAction::ReturnEffectList(), BaseAction::ReturnName(), BaseAction::ReturnStatActionType(), Debugger::SetSeverity(), target, and targets.
CalculateStat()
void StatSystem::CalculateStat (const bool IsSingleTarget_, BaseAction *const action_) [static]
Definition at line 13 of file StatSystem.cpp.
{
    BaseCalculate(IsSingleTarget_, action_);
}
References BaseCalculate().
ModifiyStat()
void StatSystem::ModifiyStat (StatSheetObject *const target_, const float value, const FString name_) [static]
This updates the stats based on the name.
Definition at line 178 of file StatSystem.cpp.
{
    if (target_->ReturnStatMap().Contains(name_))
    {
        target_->ReturnStatMap()[name_] += value;
    }
    else
    {
        Debugger::SetSeverity(MessageType::E_WARNING);
        Debugger::Warrning(name_ + " is not found in the stat sheet.", "StatSystem.cpp", __LINE__);
    }
}
References E_WARNING, StatSheetObject::ReturnStatMap(), Debugger::SetSeverity(), and Debugger::Warrning().
OnDestroy()
void StatSystem::OnDestroy () [static]
This will clearout any function data.
Definition at line 292 of file StatSystem.cpp.
{
}
operator=() [1/2]
 StatSystem& StatSystem::operator= (const StatSystem &) [delete]
operator=() [2/2]
 StatSystem& StatSystem::operator= (StatSystem &&) [delete]
RemoveModifier()
void StatSystem::RemoveModifier (StatSheetObject *const target_, BaseAction *const action_) [static], [private]
Removes the specific modification by the baseaction.
Definition at line 244 of file StatSystem.cpp.
{
    if (action_->ReturnActionType() == ACTIONTYPE::E_ITEM)
    {
        ItemAction* item = dynamic_cast<ItemAction*>(action_);
        for (auto& effect : item->ReturnEffectList())
        {
            for (auto& statMod : effect->ReturnModStatMap())
            {
                ModifiyStat(target_,-statMod.Value, statMod.Key);
            }
        }
    }
    else if (action_->ReturnActionType() == ACTIONTYPE::E_ABILITY)
    {
        AbilityAction* ability = dynamic_cast<AbilityAction*>(action_);
        for (auto& statMod : ability->ReturnModStatMap())
        {
            ModifiyStat(target_,-statMod.Value, statMod.Key);
        }
    }
    else
    {
        Debugger::SetSeverity(MessageType::E_ERROR);
        Debugger::Error(action_->ReturnName() + " does not have an modification in this action.", "StatSystem.cpp", __LINE__);
        return;
    }
}
References E_ABILITY, E_ERROR, E_ITEM, Debugger::Error(), ModifiyStat(), BaseAction::ReturnActionType(), ItemAction::ReturnEffectList(), AbilityAction::ReturnModStatMap(), BaseAction::ReturnName(), and Debugger::SetSeverity().
RemoveTmpModifier()
void StatSystem::RemoveTmpModifier (StatSheetObject *const target_, BaseAction * action_, const float duration_) [static], [private]
Removes a modification temporarly.
Definition at line 276 of file StatSystem.cpp.
{
    //This will remove a modifier then add it in a timer.
}
SetTarget()
void StatSystem::SetTarget (StatSheetObject *const target_) [static]
Sets target.
Definition at line 280 of file StatSystem.cpp.
{
    target = target_;
}
References target.
Field Documentation
target
 StatSheetObject * StatSystem::target = nullptr [static], [private]
Definition at line 12 of file StatSystem.h.
targets
TArray< StatSheetObject * > StatSystem::targets = TArray< StatSheetObject*>() [static], [private]
Definition at line 13 of file StatSystem.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ StatSystem.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/BB_Runtime_System/Private/SystemClasses/ StatSystem.cpp