Debugger Class Reference
#include <Debugger.h>
Public Member Functions
 Debugger ()=delete
 Debugger (const Debugger &)=delete
 Debugger (Debugger &&)=delete
 Debugger & operator= (const Debugger &)=delete
 Debugger & operator= (Debugger &&)=delete
Static Public Member Functions
static void Error (const FString &message_, const FString &fileName_, const int32 line_)
Sends a error log to the debugger txt file.
static void FatalError (const FString &message_, const FString &fileName_, const int32 line_)
Sends a warning log to the dugger txt file.
static void Info (const FString &message_, const FString &fileName_, const int32 line_)
Sends a info log to the debugger txt file.
static void InitDebug ()
Initiates the debugger.
static void SetSeverity (const MessageType type_)
Sets the severity.
static void Warrning (const FString &message_, const FString &fileName_, const int32 line_)
Sends a warrning log to the debugger txt file.
Static Private Member Functions
static void Log (const MessageType type_, const FString &message_, const FString &fileName_, const int32 line_)
Static Private Attributes
static MessageType currentType = MessageType::E_NONE
static FString DebugDirectory = ``
static TArray< FString > LogArray = TArray<FString>()
Detailed Description
Definition at line 17 of file Debugger.h.
Constructor & Destructor Documentation
Debugger() [1/3]
Debugger::Debugger (const Debugger &) [delete]
Debugger() [2/3]
Debugger::Debugger (Debugger &&) [delete]
Debugger() [3/3]
Debugger::Debugger () [delete]
Member Function Documentation
Error()
void Debugger::Error (const FString & message_, const FString & fileName_, const int32 line_) [static]
Sends a error log to the debugger txt file.
Definition at line 43 of file Debuger.cpp.
{
    Log(MessageType::E_ERROR,"ERROR: " + message_, fileName_, line_);
}
References E_ERROR, and Log().
FatalError()
void Debugger::FatalError (const FString & message_, const FString & fileName_, const int32 line_) [static]
Sends a warning log to the dugger txt file.
Definition at line 51 of file Debuger.cpp.
{
    Log(MessageType::E_FATAL_ERROR,"FATALERROR: " + message_, fileName_, line_);
}
References E_FATAL_ERROR, and Log().
Info()
void Debugger::Info (const FString & message_, const FString & fileName_, const int32 line_) [static]
Sends a info log to the debugger txt file.
Definition at line 39 of file Debuger.cpp.
{
    Log(MessageType::E_INFO,"INFO: " + message_, fileName_, line_);
}
References E_INFO, and Log().
InitDebug()
void Debugger::InitDebug () [static]
Initiates the debugger.
Definition at line 12 of file Debuger.cpp.
{
    DebugDirectory = FPaths::ProjectPluginsDir() + "/Battle_Box/Debug";
    if (!BattleBoxFileManager::VerifyOnCreateDirectory(DebugDirectory))
    {
        UE_LOG(LogTemp, Warning, TEXT("Something went wrong with the directory!"));
        return;
    }
    currentType = MessageType::E_FATAL_ERROR;
    UE_LOG(LogTemp, Log, TEXT("Debug Directory has been made!"));
}
References currentType, DebugDirectory, E_FATAL_ERROR, Log(), and BattleBoxFileManager::VerifyOnCreateDirectory().
Log()
void Debugger::Log (const MessageType type_, const FString & message_, const FString & fileName_, const int32 line_) [static], [private]
Definition at line 23 of file Debuger.cpp.
{
    UE_LOG(LogTemp, Log, TEXT("This Works!"));
    if (type_ <= currentType && currentType > MessageType::E_NONE)
    {
        UE_LOG(LogTemp, Log, TEXT("This Works!"));
        FString LogMessage = message_ + " in " + fileName_ + ". " + "Line: " + FString::FromInt(line_);
        FString LogFileName = "Logger.txt";
        LogArray.Add(LogMessage);
        BattleBoxFileManager::WriteTextArrayToFile(DebugDirectory, LogArray, LogFileName, true);
    }
}
References DebugDirectory, E_NONE, LogArray, and BattleBoxFileManager::WriteTextArrayToFile().
operator=() [1/2]
 Debugger& Debugger::operator= (const Debugger &) [delete]
operator=() [2/2]
 Debugger& Debugger::operator= (Debugger &&) [delete]
SetSeverity()
void Debugger::SetSeverity (const MessageType type_) [static]
Sets the severity.
Definition at line 35 of file Debuger.cpp.
{
    currentType = type_;
}
References currentType.
Warrning()
void Debugger::Warrning (const FString & message_, const FString & fileName_, const int32 line_) [static]
Sends a warrning log to the debugger txt file.
Definition at line 47 of file Debuger.cpp.
{
    Log(MessageType::E_WARNING,"WARNING: " + message_, fileName_, line_);
}
References E_WARNING, and Log().
Field Documentation
currentType
 MessageType Debugger::currentType = MessageType::E_NONE [static], [private]
Definition at line 22 of file Debugger.h.
DebugDirectory
FString Debugger::DebugDirectory = `` [static], [private]
Definition at line 23 of file Debugger.h.
LogArray
TArray< FString > Debugger::LogArray = TArray<FString>() [static], [private]
Definition at line 21 of file Debugger.h.
The documentation for this class was generated from the following files:
Battle_Box/Private/ Debugger.h
Battle_Box/Private/ Debuger.cpp