CommandAction Class Reference
#include <CommandAction.h>
Public Member Functions
 CommandAction ()
 CommandAction (CommandAction *const other_)
 CommandAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const WEAPONTYPE currentWeap_, BaseAction *const command_)
void OnDestroy ()
 BaseAction * ReturnAction () const
Return acton.
uint32 ReturnActionID () const
Return Action ID.
 ACTIONTYPE ReturnActionType () const
Return action type.
FString ReturnDiscription () const
Return discription.
 INTERACTIONTYPE ReturnInteractionType () const
Return Interaction type.
FString ReturnName () const
Return Name.
 STATACTION ReturnStatActionType () const
Returns the stat action type.
 TARGETTYPE ReturnTargetType () const
Return target type.
 WEAPONTYPE ReturnWeaponType () const
Return weapon type.
void SetActionID (const uint32 actionID_)
Sets action ID.
void SetActionType (const ACTIONTYPE type_)
Sets Actiontype.
void SetCommand (BaseAction *action_)
Sets the command object.
void SetDiscription (const FString discription_)
Sets Discription.
void SetInteractionType (const INTERACTIONTYPE type_)
Sets interaction type.
void SetName (const FString name_)
Sets Name.
void SetStatActionType (const STATACTION type_)
Set Stat Action type.
void SetTargetType (const TARGETTYPE type_)
Sets target type.
void SetWeaponType (WEAPONTYPE type_)
Sets the weapon type the item is.
 ~CommandAction ()
Private Attributes
 ACTIONTYPE action
uint32 actionID
 BaseAction * command
 WEAPONTYPE currentweapon
FString discription
 INTERACTIONTYPE interaction
bool isActionCommand
FString name
 STATACTION statAction
 TARGETTYPE target
Detailed Description
Definition at line 16 of file CommandAction.h.
Constructor & Destructor Documentation
CommandAction() [1/3]
CommandAction::CommandAction ()
Definition at line 6 of file CommandAction.cpp.
                             : command(nullptr)
{
    SetName("");
    SetDiscription("");
    SetActionType(ACTIONTYPE::E_NONE);
    SetTargetType(TARGETTYPE::E_NONE);
    SetInteractionType(INTERACTIONTYPE::E_NONE);
    SetActionID(00);
    currentweapon = WEAPONTYPE::E_NONE;
}
References currentweapon, E_NONE, BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), and BaseAction::SetTargetType().
CommandAction() [2/3]
CommandAction::CommandAction (const FString name_, const FString discription_, const ACTIONTYPE action_, const TARGETTYPE target_, const INTERACTIONTYPE interaction_, const uint32 actionID_, TMap< FString, float > statMap_, const WEAPONTYPE currentWeap_, BaseAction *const command_)
Definition at line 16 of file CommandAction.cpp.
{
    SetName(name_);
    SetDiscription(discription_);
    SetActionType(action_);
    SetTargetType(target_);
    SetInteractionType(interaction_);
    SetActionID(actionID_);
    currentweapon = currentWeap_;
    command = command_;
}
References command, currentweapon, BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), and BaseAction::SetTargetType().
CommandAction() [3/3]
CommandAction::CommandAction (CommandAction *const other_)
Definition at line 27 of file CommandAction.cpp.
{
    SetName(other_->ReturnName());
    SetDiscription(other_->ReturnDiscription());
    SetActionType(other_->ReturnActionType());
    SetTargetType(other_->ReturnTargetType());
    SetInteractionType(other_->ReturnInteractionType());
    SetActionID(other_->ReturnActionID());
    currentweapon = ReturnWeaponType();
    command = ReturnAction();
}
References command, currentweapon, ReturnAction(), BaseAction::ReturnActionID(), BaseAction::ReturnActionType(), BaseAction::ReturnDiscription(), BaseAction::ReturnInteractionType(), BaseAction::ReturnName(), BaseAction::ReturnTargetType(), ReturnWeaponType(), BaseAction::SetActionID(), BaseAction::SetActionType(), BaseAction::SetDiscription(), BaseAction::SetInteractionType(), BaseAction::SetName(), and BaseAction::SetTargetType().
~CommandAction()
CommandAction::~CommandAction ()
Definition at line 62 of file CommandAction.cpp.
{
    OnDestroy();
}
References OnDestroy().
Member Function Documentation
OnDestroy()
void CommandAction::OnDestroy ()
Definition at line 54 of file CommandAction.cpp.
{
    if(command)
    {
        delete command;
        command = nullptr;
    }
}
References command.
ReturnAction()
 BaseAction * CommandAction::ReturnAction () const
Return acton.
Definition at line 50 of file CommandAction.cpp.
{
    return command;
}
References command.
ReturnActionID()
uint32 BaseAction::ReturnActionID () const [inherited]
Return Action ID.
Definition at line 85 of file BaseAction.cpp.
{
    return actionID;
}
References BaseAction::actionID.
ReturnActionType()
 ACTIONTYPE BaseAction::ReturnActionType () const [inherited]
Return action type.
Definition at line 69 of file BaseAction.cpp.
{
    return action;
}
References BaseAction::action.
ReturnDiscription()
FString BaseAction::ReturnDiscription () const [inherited]
Return discription.
Definition at line 65 of file BaseAction.cpp.
{
    return discription;
}
References BaseAction::discription.
ReturnInteractionType()
 INTERACTIONTYPE BaseAction::ReturnInteractionType () const [inherited]
Return Interaction type.
Definition at line 77 of file BaseAction.cpp.
{
    return interaction;
}
References BaseAction::interaction.
ReturnName()
FString BaseAction::ReturnName () const [inherited]
Return Name.
ReturnStatActionType()
 STATACTION BaseAction::ReturnStatActionType () const [inherited]
Returns the stat action type.
Definition at line 81 of file BaseAction.cpp.
{
    return statAction;
}
References BaseAction::statAction.
ReturnTargetType()
 TARGETTYPE BaseAction::ReturnTargetType () const [inherited]
Return target type.
Definition at line 73 of file BaseAction.cpp.
{
    return target;
}
References BaseAction::target.
ReturnWeaponType()
 WEAPONTYPE CommandAction::ReturnWeaponType () const
Return weapon type.
Definition at line 46 of file CommandAction.cpp.
{
    return currentweapon;
}
References currentweapon.
SetActionID()
void BaseAction::SetActionID (const uint32 actionID_) [inherited]
Sets action ID.
Definition at line 57 of file BaseAction.cpp.
{
    actionID = actionID_;
}
References BaseAction::actionID.
SetActionType()
void BaseAction::SetActionType (const ACTIONTYPE type_) [inherited]
Sets Actiontype.
Definition at line 41 of file BaseAction.cpp.
{
    action = type_;
}
References BaseAction::action.
SetCommand()
void CommandAction::SetCommand (BaseAction * action_)
Sets the command object.
Definition at line 42 of file CommandAction.cpp.
{
    command = action_;
}
References command.
SetDiscription()
void BaseAction::SetDiscription (const FString discription_) [inherited]
Sets Discription.
Definition at line 37 of file BaseAction.cpp.
{
    discription = discription_;
}
References BaseAction::discription.
SetInteractionType()
void BaseAction::SetInteractionType (const INTERACTIONTYPE type_) [inherited]
Sets interaction type.
Definition at line 49 of file BaseAction.cpp.
{
    interaction = type_;
}
References BaseAction::interaction.
SetName()
void BaseAction::SetName (const FString name_) [inherited]
Sets Name.
Definition at line 33 of file BaseAction.cpp.
{
    name = name_;
}
References BaseAction::name.
SetStatActionType()
void BaseAction::SetStatActionType (const STATACTION type_) [inherited]
Set Stat Action type.
Definition at line 53 of file BaseAction.cpp.
{
    statAction = type_;
}
References BaseAction::statAction.
SetTargetType()
void BaseAction::SetTargetType (const TARGETTYPE type_) [inherited]
Sets target type.
Definition at line 45 of file BaseAction.cpp.
{
    target = type_;
}
References BaseAction::target.
SetWeaponType()
void CommandAction::SetWeaponType (WEAPONTYPE type_)
Sets the weapon type the item is.
Definition at line 38 of file CommandAction.cpp.
{
    currentweapon = type_;
}
References currentweapon.
Field Documentation
action
 ACTIONTYPE BaseAction::action [private], [inherited]
Definition at line 70 of file BaseAction.h.
actionID
uint32 BaseAction::actionID [private], [inherited]
Definition at line 74 of file BaseAction.h.
command
 BaseAction* CommandAction::command [private]
Definition at line 21 of file CommandAction.h.
currentweapon
 WEAPONTYPE CommandAction::currentweapon [private]
Definition at line 20 of file CommandAction.h.
discription
FString BaseAction::discription [private], [inherited]
Definition at line 69 of file BaseAction.h.
interaction
 INTERACTIONTYPE BaseAction::interaction [private], [inherited]
Definition at line 73 of file BaseAction.h.
isActionCommand
bool CommandAction::isActionCommand [private]
Definition at line 19 of file CommandAction.h.
name
FString BaseAction::name [private], [inherited]
Definition at line 68 of file BaseAction.h.
statAction
 STATACTION BaseAction::statAction [private], [inherited]
Definition at line 72 of file BaseAction.h.
target
 TARGETTYPE BaseAction::target [private], [inherited]
Definition at line 71 of file BaseAction.h.
The documentation for this class was generated from the following files:
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ActionClasses/ CommandAction.h
D:/UNrealProjects/Battl_Box_Project/Plugins/Battle_Box/Source/Battle_Box/Private/ActionClasses/ CommandAction.cpp